package com.example.fyp_patient

object testData {

    val threeWord = hashMapOf(
        "1,25 dihydroxyvitamin D" to "1,25 dihydroxyvitamin D",
        "24-Hour Urine Protein" to "24-Hour Urine Protein",
        "4q12 (CHIC2) deletion" to "4q12 (CHIC2) deletion",
        "ACTH Stimulation Test" to "ACTH Stimulation Test",
        "ACTH Stimulation Test" to "ACTH Stimulation Test",
        "ACTH challenge test" to "ACTH challenge test",
        "ACTH stim test" to "ACTH stim test",
        "ALK Gene Fusion" to "ALK Gene Fusion",
        "ALK Gene Rearrangement" to "ALK Gene Rearrangement",
        "AMH Hormone Test" to "AMH Hormone Test",
        "APOE Cardiac Risk" to "APOE Cardiac Risk",
        "ARV Resistance Testing" to "ARV Resistance Testing",
        "Acidosis and Alkalosis" to "Acidosis and Alkalosis",
        "Activated Coagulation Time" to "Activated Coagulation Time",
        "Acute Promyelocytic Leukemia" to "Acute Promyelocytic Leukemia",
        "Adrenocorticotropic Hormone (ACTH)" to "Adrenocorticotropic Hormone (ACTH)",
        "Adrenocorticotropic Hormone (ACTH)" to "Adrenocorticotropic Hormone (ACTH)",
        "Aerobic Wound Culture" to "Aerobic Wound Culture",
        "Alanine Aminotransferase (ALT)" to "Alanine Aminotransferase (ALT)",
        "Alanine Aminotransferase (ALT)" to "Alanine Aminotransferase (ALT)",
        "Alcohol Use Disorder" to "Alcoholism",
        "Aldosterone and Renin" to "Aldosterone and Renin",
        "Aldosterone and Renin" to "Aldosterone and Renin",
        "Alkaline Phosphatase (ALP)" to "Alkaline Phosphatase (ALP)",
        "Alkaline Phosphatase (ALP)" to "Alkaline Phosphatase (ALP)",
        "Alkaline Phosphatase Isoenzymes" to "Alkaline Phosphatase Isoenzymes",
        "Allergy Blood Testing" to "Allergy Blood Testing",
        "Allergy Blood Testing" to "Allergy Blood Testing",
        "Amniotic Fluid Analysis" to "Amniotic Fluid Analysis",
        "Amniotic Fluid Analysis" to "Amniotic Fluid Analysis",
        "Anaerobic Wound Culture" to "Anaerobic Wound Culture",
        "Angiotensin-Converting Enzyme (ACE)" to "Angiotensin-Converting Enzyme (ACE)",
        "Angiotensin-Converting Enzyme (ACE)" to "Angiotensin-Converting Enzyme (ACE)",
        "Anti-Beta-2 Glycoprotein 1" to "Anti-Beta-2 Glycoprotein 1",
        "Anti-P450 2D6 Antibody" to "Anti-LKM-1",
        "Anti-P450 2D6 Antibody" to "Anti-LKM-1",
        "Anti-P450 2D6 Antibody" to "Anti-P450 2D6 Antibody",
        "Anti-Sjögren Syndrome A" to "Anti-Sjögren Syndrome A",
        "Anti-Sjögren Syndrome B" to "Anti-Sjögren Syndrome B",
        "Anti-Smooth Muscle Antibody" to "Anti-Smooth Muscle Antibody",
        "Anti-cyclic Citrullinated Peptide" to "Anti-cyclic Citrullinated Peptide",
        "Anti-deamidated Gliadin Peptides" to "Anti-deamidated Gliadin Peptides",
        "Antibody to ds-DNA" to "Anti-dsDNA",
        "Antibody to ds-DNA" to "Anti-dsDNA",
        "Anti-factor Xa Heparin" to "Anti-factor Xa Heparin",
        "Anti-parietal Cell Antibody" to "Anti-parietal Cell Antibody",
        "Anti-tissue Transglutaminase Antibody" to "Anti-tissue Transglutaminase Antibody",
        "Antibiotic Susceptibility Testing" to "Antibiotic Susceptibility Testing",
        "Antibiotic Susceptibility Testing" to "Antibiotic Susceptibility Testing",
        "Antibody ID, RBC" to "Antibody ID, RBC",
        "Antibody to ds-DNA" to "Antibody to ds-DNA",
        "Antidiuretic Hormone (ADH)" to "Antidiuretic Hormone (ADH)",
        "Antidiuretic Hormone (ADH)" to "Antidiuretic Hormone (ADH)",
        "Antinuclear Antibody (ANA)" to "Antinuclear Antibody (ANA)",
        "Antinuclear Antibody (ANA)" to "Antinuclear Antibody (ANA)",
        "Antinuclear Antibody Screen" to "Antinuclear Antibody Screen",
        "Antistreptolysin O (ASO)" to "Antistreptolysin O (ASO)",
        "Antistreptolysin O (ASO)" to "Antistreptolysin O (ASO)",
        "Functional Antithrombin III" to "Antithrombin",
        "Functional Antithrombin III" to "Antithrombin",
        "Arterial Blood Gases" to "Arterial Blood Gases",
        "Arthropod-borne Virus Testing" to "Arthropod-borne Virus Testing",
        "Aspartate Aminotransferase (AST)" to "Aspartate Aminotransferase (AST)",
        "Aspartate Aminotransferase (AST)" to "Aspartate Aminotransferase (AST)",
        "Immunoglobulin Gene Rearrangement" to "BCGR",
        "BNP and NT-proBNP" to "BNP and NT-proBNP",
        "BNP and NT-proBNP" to "BNP and NT-proBNP",
        "Bacterial Culture, respiratory" to "Bacterial Culture, respiratory",
        "Bacterial Culture, stool" to "Bacterial Culture, stool",
        "Bacterial Sputum Culture" to "Bacterial Sputum Culture",
        "Bacterial Wound Culture" to "Bacterial Wound Culture",
        "Bacterial Wound Culture" to "Bacterial Wound Culture",
        "Benign Prostatic Hyperplasia" to "Benign Prostatic Hyperplasia",
        "Beta 2GP1 Ab" to "Beta 2GP1 Ab",
        "Beta-hemolytic Strep Culture" to "Beta-hemolytic Strep Culture",
        "Bicarbonate (Total CO2)" to "Bicarbonate (Total CO2)",
        "Bicarbonate (Total CO2)" to "Bicarbonate (Total CO2)",
        "Blood Alcohol Content" to "Blood Alcohol Content",
        "Blood Alcohol Level" to "Blood Alcohol Level",
        "Blood Clotting Factors" to "Blood Clotting Factors",
        "Blood Glucose (Fasting)" to "Blood Glucose (Fasting)",
        "Blood Glucose (Random)" to "Blood Glucose (Random)",
        "Blood Lead Level" to "Blood Lead Level",
        "Blood Lead Test" to "Blood Lead Test",
        "Body Fluid Testing" to "Body Fluid Testing",
        "Body Fluid Testing" to "Body Fluid Testing",
        "Bone Formation Markers" to "Bone Formation Markers",
        "Bone Marrow Disorders" to "Bone Marrow Disorders",
        "Bone Marrow Examination" to "Bone Marrow Examination",
        "Bone Resorption Markers" to "Bone Resorption Markers",
        "Bone Turnover Tests" to "Bone Turnover Tests",
        "Bone-specific Alkaline Phosphatase" to "Bone-specific Alkaline Phosphatase",
        "Borrelia Antibodies, IgM/IgG" to "Borrelia Antibodies, IgM/IgG",
        "Brain Natriuretic Peptide" to "Brain Natriuretic Peptide",
        "C & S" to "C & S",
        "C-Reactive Protein (CRP)" to "C-Reactive Protein (CRP)",
        "C-Reactive Protein (CRP)" to "C-Reactive Protein (CRP)",
        "Connecting Peptide Insulin" to "C-peptide",
        "Connecting Peptide Insulin" to "C-peptide",
        "CF DNA Analysis" to "CF DNA Analysis",
        "CFTR Mutation Analysis" to "CFTR Mutation Analysis",
        "CMV Blood Test" to "CMV Blood Test",
        "COVID-19 Ag test" to "COVID-19 Ag test",
        "COVID-19 Antigen test" to "COVID-19 Antigen test",
        "CSF Protein Electrophoresis" to "CSF Protein Electrophoresis",
        "Calcidiol (25-hydroxyvitamin D)" to "Calcidiol (25-hydroxyvitamin D)",
        "Calcifidiol (25-hydroxy-vitamin D)" to "Calcifidiol (25-hydroxy-vitamin D)",
        "Calcofluor White Stain" to "Calcofluor White Stain",
        "Cancer Antigen 19-9" to "Cancer Antigen 19-9",
        "Cancer Antigen 19-9" to "Cancer Antigen 19-9",
        "Carbohydrate Antigen 19-9" to "Carbohydrate Antigen 19-9",
        "Carbon Dioxide Content" to "Carbon Dioxide Content",
        "Carcinoembryonic Antigen (CEA)" to "Carcinoembryonic Antigen (CEA)",
        "Carcinoembryonic Antigen (CEA)" to "Carcinoembryonic Antigen (CEA)",
        "Cardiac Risk Assessment" to "Cardiac Risk Assessment",
        "Cardiac Risk Assessment" to "Cardiac Risk Assessment",
        "Cardiovascular Disease (CVD)" to "Cardiovascular Disease (CVD)",
        "Cell-Free Fetal DNA" to "Cell-Free Fetal DNA",
        "Chemical Terrorism Agents" to "Chemical Terrorism Agents",
        "Chlamydia/GC STD Panel" to "Chlamydia/GC STD Panel",
        "Cholecalciferol (Vitamin D3)" to "Cholecalciferol (Vitamin D3)",
        "Chromosome Analysis (Karyotyping)" to "Chromosome Analysis (Karyotyping)",
        "Chromosome Analysis (Karyotyping)" to "Chromosome Analysis (Karyotyping)",
        "Chronic Fatigue Syndrome" to "Chronic Fatigue Syndrome",
        "Clopidogrel (CYP2C19 Genotyping)" to "Clopidogrel (CYP2C19 Genotyping)",
        "Clopidogrel (CYP2C19 Genotyping)" to "Clopidogrel (CYP2C19 Genotyping)",
        "Clopidogrel Pharmacogenetic Testing" to "Clopidogrel Pharmacogenetic Testing",
        "Congenital Adrenal Hyperplasia" to "Congenital Adrenal Hyperplasia",
        "Congestive Heart Failure" to "Congestive Heart Failure",
        "Connecting Peptide Insulin" to "Connecting Peptide Insulin",
        "Continuous Glucose Monitoring" to "Continuous Glucose Monitoring",
        "Continuous Glucose Monitoring" to "Continuous Glucose Monitoring",
        "Coronary Risk Panel" to "Coronary Risk Panel",
        "Coronavirus (COVID-19) Testing" to "Coronavirus (COVID-19) Testing",
        "Coronavirus (COVID-19) Testing" to "Coronavirus (COVID-19) Testing",
        "Coronavirus 2019 Test" to "Coronavirus 2019 Test",
        "Dexamethasone Suppression Test" to "Cortisol",
        "ACTH Stimulation Test" to "Cortisol",
        "Dexamethasone Suppression Test" to "Cortisol",
        "ACTH Stimulation Test" to "Cortisol",
        "Creatine Kinase (CK)" to "Creatine Kinase (CK)",
        "Creatine Kinase (CK)" to "Creatine Kinase (CK)",
        "Creatinine Clearance, Urine" to "Creatinine Clearance",
        "Creatinine Clearance, Urine" to "Creatinine Clearance",
        "Creatinine Clearance, Urine" to "Creatinine Clearance, Urine",
        "Culture and Sensitivity " to "Culture and Sensitivity ",
        "Cystic Fibrosis Genotyping" to "Cystic Fibrosis Genotyping",
        "Cytomegalovirus (CMV) Tests" to "Cytomegalovirus (CMV) Tests",
        "Cytomegalovirus (CMV) Tests" to "Cytomegalovirus (CMV) Tests",
        "Fibrin Degradation Fragment" to "D-dimer",
        "Fibrin Degradation Fragment" to "D-dimer",
        "Dengue Fever Antibodies" to "Dengue Fever Antibodies",
        "Dengue Fever Testing" to "Dengue Fever Testing",
        "Dengue Fever Testing" to "Dengue Fever Testing",
        "Dengue Fever Virus" to "Dengue Fever Virus",
        "Des-gamma-carboxy prothrombin (DCP)" to "Des-gamma-carboxy prothrombin (DCP)",
        "Des-gamma-carboxy prothrombin (DCP)" to "Des-gamma-carboxy prothrombin (DCP)",
        "Dexamethasone Suppression Test" to "Dexamethasone Suppression Test",
        "Differential Blood Count" to "Differential Blood Count",
        "Serum Digoxin Level" to "Digoxin",
        "Serum Digoxin Level" to "Digoxin",
        "Direct Antiglobulin Test" to "Direct Antiglobulin Test",
        "Direct Antiglobulin Test" to "Direct Antiglobulin Test",
        "Direct Coombs Test" to "Direct Coombs Test",
        "Direct LDL Cholesterol" to "Direct LDL Cholesterol",
        "Direct LDL Cholesterol" to "Direct LDL Cholesterol",
        "Disaccharide Absorption Test" to "Disaccharide Absorption Test",
        "Drug Abuse Testing" to "Drug Abuse Testing",
        "Drug Abuse Testing" to "Drug Abuse Testing",
        "Drug Resistance Testing" to "Drug Resistance Testing",
        "E. coli O157" to "E. coli O157",
        "E. coli non-O157" to "E. coli non-O157",
        "EGFR Mutation Testing" to "EGFR Mutation Testing",
        "EGFR Mutation Testing" to "EGFR Mutation Testing",
        "EML4-ALK Fusion Protein" to "EML4-ALK Fusion Protein",
        "Ebola Virus Infection" to "Ebola Virus Infection",
        "Serum Protein Electrophoresis" to "Electrophoresis",
        "Urine Protein Electrophoresis" to "Electrophoresis",
        "CSF Protein Electrophoresis" to "Electrophoresis",
        "Enteric Pathogen Panel" to "Enteric Pathogen Panel",
        "Ergocalciferol (Vitamin D2)" to "Ergocalciferol (Vitamin D2)",
        "Blood Alcohol Level" to "Ethanol",
        "Blood Alcohol Content" to "Ethanol",
        "Blood Alcohol Level" to "Ethanol",
        "Blood Alcohol Content" to "Ethanol",
        "Excessive Clotting Disorders" to "Excessive Clotting Disorders",
        "4q12 (CHIC2) deletion" to "FIP1L1-PDGFRA",
        "PDGFRA-FIP1L1 gene rearrangement" to "FIP1L1-PDGFRA",
        "4q12 (CHIC2) deletion" to "FIP1L1-PDGFRA",
        "PDGFRA-FIP1L1 gene rearrangement" to "FIP1L1-PDGFRA",
        "Factor I Assay" to "Factor I Assay",
        "Factor II 20210" to "Factor II 20210",
        "Factor II Mutation" to "Factor II Mutation",
        "Factor V R506Q" to "Factor V R506Q",
        "Fasting Lipid Panel" to "Fasting Lipid Panel",
        "Fecal Immunochemical Test" to "Fecal Immunochemical Test",
        "Fecal Pancreatic Elastase" to "Fecal Pancreatic Elastase",
        "Fecal WBC Non-microscopic" to "Fecal WBC Non-microscopic",
        "Fetal Fibronectin (fFN)" to "Fetal Fibronectin (fFN)",
        "Fetal Fibronectin (fFN)" to "Fetal Fibronectin (fFN)",
        "Fibrin Degradation Fragment" to "Fibrin Degradation Fragment",
        "Factor I Assay" to "Fibrinogen",
        "Fibrinogen Activity (Functional)" to "Fibrinogen",
        "Factor I Assay" to "Fibrinogen",
        "Fibrinogen Activity (Functional)" to "Fibrinogen",
        "Fibrinogen Activity (Functional)" to "Fibrinogen Activity (Functional)",
        "First Trimester Screening" to "First Trimester Screening",
        "First Trimester Screening" to "First Trimester Screening",
        "Fluorescent Antinuclear Antibody" to "Fluorescent Antinuclear Antibody",
        "Follicle-stimulating Hormone (FSH)" to "Follicle-stimulating Hormone (FSH)",
        "Follicle-stimulating Hormone (FSH)" to "Follicle-stimulating Hormone (FSH)",
        "Fragile X PCR" to "Fragile X PCR",
        "Fragile X Syndrome" to "Fragile X Syndrome",
        "Free Erythrocyte Protoporphyrin" to "Free Erythrocyte Protoporphyrin",
        "Free Kappa/Lambda Ratio" to "Free Kappa/Lambda Ratio",
        "Free Light Chains" to "Free Light Chains",
        "Free Metanephrines, urine" to "Free Metanephrines, urine",
        "Free Valproic Acid" to "Free Valproic Acid",
        "Glycated Serum Protein" to "Fructosamine",
        "Glycated Serum Protein" to "Fructosamine",
        "Functional Antithrombin III" to "Functional Antithrombin III",
        "Fungal Molecular Tests" to "Fungal Molecular Tests",
        "RBC G6PD test" to "G6PD",
        "RBC G6PD test" to "G6PD",
        "Gamma-Glutamyl Transferase (GGT)" to "Gamma-Glutamyl Transferase (GGT)",
        "Gamma-Glutamyl Transferase (GGT)" to "Gamma-Glutamyl Transferase (GGT)",
        "Gastrointestinal Pathogens Panel" to "Gastrointestinal Pathogens Panel",
        "Gastrointestinal Pathogens Panel" to "Gastrointestinal Pathogens Panel",
        "Genital Human Papillomavirus" to "Genital Human Papillomavirus",
        "Glomerular Filtration Rate" to "Glomerular Filtration Rate",
        "Glucose Tolerance Test" to "Glucose Tolerance Test",
        "Glucose Tolerance Test" to "Glucose Tolerance Test",
        "Glutamate dehydrogenase test" to "Glutamate dehydrogenase test",
        "Glycated Serum Protein" to "Glycated Serum Protein",
        "Group B Strep" to "Group B Strep",
        "Group B Streptococcus" to "Group B Streptococcus",
        "HIT PF4 Antibody" to "HIT PF4 Antibody",
        "HIV RNA Test" to "HIV RNA Test",
        "HIV Screening Tests" to "HIV Screening Tests",
        "HIV Viral Load" to "HIV Viral Load",
        "HIV Viral Load" to "HIV Viral Load",
        "HIV by PCR" to "HIV by PCR",
        "HSV by PCR" to "HSV by PCR",
        "HTLV-I/II by PCR" to "HTLV-I/II by PCR",
        "Packed Cell Volume" to "Hematocrit",
        "Packed Cell Volume" to "Hematocrit",
        "Heparin Associated Antibody" to "Heparin Associated Antibody",
        "Heparin Induced Antibody" to "Heparin Induced Antibody",
        "Hepatitis A Testing" to "Hepatitis A Testing",
        "Hepatitis A Testing" to "Hepatitis A Testing",
        "Hepatitis B Testing" to "Hepatitis B Testing",
        "Hepatitis B Testing" to "Hepatitis B Testing",
        "Hepatitis C Antibody" to "Hepatitis C Antibody",
        "Hepatitis C Testing" to "Hepatitis C Testing",
        "Hepatitis C Testing" to "Hepatitis C Testing",
        "Hepatitis Screening Panel" to "Hepatitis Screening Panel",
        "Herpes CSF Test" to "Herpes CSF Test",
        "Herpes Simplex Serology" to "Herpes Simplex Serology",
        "Heterophile Antibody Test" to "Heterophile Antibody Test",
        "Hg (chemical symbol)" to "Hg (chemical symbol)",
        "Plasma Total Homocysteine" to "Homocysteine",
        "Homocysteine Cardiac Risk" to "Homocysteine",
        "Plasma Total Homocysteine" to "Homocysteine",
        "Homocysteine Cardiac Risk" to "Homocysteine",
        "Homocysteine Cardiac Risk" to "Homocysteine Cardiac Risk",
        "Hormone Receptor Status" to "Hormone Receptor Status",
        "Human Fecal Elastase-1" to "Human Fecal Elastase-1",
        "Human Growth Hormone" to "Human Growth Hormone",
        "Hydrogen Breath Test" to "Hydrogen Breath Test",
        "IGRA TB Test" to "IGRA TB Test",
        "IGRA TB Test" to "IGRA TB Test",
        "Immune Checkpoint Inhibitor" to "Immune Checkpoint Inhibitor",
        "Immunoglobulin A, Total" to "Immunoglobulin A, Total",
        "Immunoglobulin Gene Rearrangement" to "Immunoglobulin Gene Rearrangement",
        "Immunoreactive Trypsinogen (IRT)" to "Immunoreactive Trypsinogen (IRT)",
        "Immunoreactive Trypsinogen (IRT)" to "Immunoreactive Trypsinogen (IRT)",
        "Indirect Antiglobulin Test" to "Indirect Antiglobulin Test",
        "Indirect Coombs Test" to "Indirect Coombs Test",
        "Inflammatory Bowel Disease" to "Inflammatory Bowel Disease",
        "Influenza Viral Culture" to "Influenza Viral Culture",
        "Insulin Autoantibodies (IAA)" to "Insulin Autoantibodies (IAA)",
        "Insulinoma-Associated-2 Autoantibodies (IA-2A)" to "Insulinoma-Associated-2 Autoantibodies (IA-2A)",
        "Intermittently Scanning CGM " to "Intermittently Scanning CGM ",
        "Interstitial Glucose Monitoring" to "Interstitial Glucose Monitoring",
        "Intrinsic Factor Antibody" to "Intrinsic Factor Antibody",
        "Intrinsic Factor Antibody" to "Intrinsic Factor Antibody",
        "Iontophoretic Sweat Test" to "Iontophoretic Sweat Test",
        "Iron Binding Capacity" to "Iron Binding Capacity",
        "Janus Kinase 2" to "Janus Kinase 2",
        "Joint Fluid Analysis" to "Joint Fluid Analysis",
        "Juvenile Rheumatoid Arthritis" to "Juvenile Rheumatoid Arthritis",
        "Kidney Function Panel" to "Kidney Function Panel",
        "Kidney Stone Analysis" to "Kidney Stone Analysis",
        "Kidney Stone Testing" to "Kidney Stone Testing",
        "Kidney Stone Testing" to "Kidney Stone Testing",
        "LA Sensitive PTT" to "LA Sensitive PTT",
        "LDL Particle Number" to "LDL Particle Number",
        "Lactate Dehydrogenase (LD)" to "Lactate Dehydrogenase (LD)",
        "Lactate Dehydrogenase (LD)" to "Lactate Dehydrogenase (LD)",
        "Fecal WBC Non-microscopic" to "Lactoferrin",
        "Fecal WBC Non-microscopic" to "Lactoferrin",
        "Lactose Breath Test" to "Lactose Breath Test",
        "Lactose Intolerance Test" to "Lactose Intolerance Test",
        "Lactose Tolerance Tests" to "Lactose Tolerance Tests",
        "Lactose Tolerance Tests" to "Lactose Tolerance Tests",
        "Blood Lead Test" to "Lead",
        "Blood Lead Level" to "Lead",
        "Blood Lead Test" to "Lead",
        "Blood Lead Level" to "Lead",
        "Leukocyte Differential Count" to "Leukocyte Differential Count",
        "Light Chains, Free" to "Light Chains, Free",
        "Coronary Risk Panel" to "Lipid Profile",
        "Fasting Lipid Panel" to "Lipid Profile",
        "Non-fasting Lipid Panel" to "Lipid Profile",
        "Lipoprotein little a" to "Lipoprotein little a",
        "Liver Function Tests" to "Liver Function Tests",
        "Platelet-activating Factor Acetylhydrolase" to "Lp-PLA2",
        "Platelet-activating Factor Acetylhydrolase" to "Lp-PLA2",
        "LA Sensitive PTT" to "Lupus",
        "Lupus Anticoagulant Testing" to "Lupus Anticoagulant Testing",
        "Lupus Anticoagulant Testing" to "Lupus Anticoagulant Testing",
        "Luteinizing Hormone (LH)" to "Luteinizing Hormone (LH)",
        "Luteinizing Hormone (LH)" to "Luteinizing Hormone (LH)",
        "Lyme Antibodies Detection" to "Lyme Antibodies Detection",
        "Lyme Disease Tests" to "Lyme Disease Tests",
        "Lyme Disease Tests" to "Lyme Disease Tests",
        "MTHFR DNA Testing" to "MTHFR DNA Testing",
        "Marijuana (THC) Testing " to "Marijuana (THC) Testing ",
        "Marijuana (THC) Testing " to "Marijuana (THC) Testing ",
        "Mast Cell Tryptase" to "Mast Cell Tryptase",
        "Maternal Serum AFP" to "Maternal Serum AFP",
        "Mean Platelet Volume" to "Mean Platelet Volume",
        "Meningitis and Encephalitis" to "Meningitis and Encephalitis",
        "Hg (chemical symbol)" to "Mercury",
        "Hg (chemical symbol)" to "Mercury",
        "Mononuclear Heterophile Test" to "Mononuclear Heterophile Test",
        "Mononucleosis (Mono) Test" to "Mononucleosis (Mono) Test",
        "Mononucleosis (Mono) Test" to "Mononucleosis (Mono) Test",
        "Mononucleosis Spot Test" to "Mononucleosis Spot Test",
        "MuSK Antibody, IgG" to "MuSK Antibody, IgG",
        "Multi-pathogen Molecular Assay" to "Multi-pathogen Molecular Assay",
        "Multi-target stool DNA" to "Multi-target stool DNA",
        "Multiple Marker Test" to "Multiple Marker Test",
        "Multiplex Respiratory Panel" to "Multiplex Respiratory Panel",
        "Myasthenia Gravis Antibodies" to "Myasthenia Gravis Antibodies",
        "Mycoplasma by PCR" to "Mycoplasma",
        "Mycoplasma by PCR" to "Mycoplasma",
        "Mycoplasma DNA Testing" to "Mycoplasma DNA Testing",
        "Mycoplasma by PCR" to "Mycoplasma by PCR",
        "Mycoplasma pneumoniae Culture" to "Mycoplasma pneumoniae Culture",
        "Müllerian Inhibiting Factor" to "Müllerian Inhibiting Factor",
        "NMR Particle Test" to "NMR Particle Test",
        "Neural Tube Defects" to "Neural Tube Defects",
        "Nicotine and Cotinine" to "Nicotine and Cotinine",
        "Nicotine and Cotinine" to "Nicotine and Cotinine",
        "Non-Invasive Prenatal Testing" to "Non-Invasive Prenatal Testing",
        "Non-fasting Lipid Panel" to "Non-fasting Lipid Panel",
        "Nontuberculous Mycobacteria Infections" to "Nontuberculous Mycobacteria Infections",
        "Oral Lactose Tolerance" to "Oral Lactose Tolerance",
        "Immune Checkpoint Inhibitor" to "PD-L1",
        "Immune Checkpoint Inhibitor" to "PD-L1",
        "PDGFRA-FIP1L1 gene rearrangement" to "PDGFRA-FIP1L1 gene rearrangement",
        "Acute Promyelocytic Leukemia" to "PML-RARA",
        "Acute Promyelocytic Leukemia" to "PML-RARA",
        "Presenilin 1 Gene" to "PSEN1",
        "Presenilin 1 Gene" to "PSEN1",
        "Packed Cell Volume" to "Packed Cell Volume",
        "Pantothenic acid (B5)" to "Pantothenic acid (B5)",
        "Parathyroid Hormone (PTH)" to "Parathyroid Hormone (PTH)",
        "Parathyroid Hormone (PTH)" to "Parathyroid Hormone (PTH)",
        "Parietal Cell Antibody" to "Parietal Cell Antibody",
        "Parietal Cell Antibody" to "Parietal Cell Antibody",
        "Pelvic Inflammatory Disease" to "Pelvic Inflammatory Disease",
        "Pericardial Fluid Analysis" to "Pericardial Fluid Analysis",
        "Pericardial Fluid Analysis" to "Pericardial Fluid Analysis",
        "Peritoneal Fluid Analysis" to "Peritoneal Fluid Analysis",
        "Peritoneal Fluid Analysis" to "Peritoneal Fluid Analysis",
        "Plasma Free Metanephrines" to "Plasma Free Metanephrines",
        "Plasma Free Metanephrines" to "Plasma Free Metanephrines",
        "Plasma Total Homocysteine" to "Plasma Total Homocysteine",
        "Platelet Aggregation Studies" to "Platelet Aggregation Studies",
        "Platelet Distribution Width" to "Platelet Distribution Width",
        "Platelet Function Assay" to "Platelet Function Assay",
        "Platelet Function Tests" to "Platelet Function Tests",
        "Platelet Function Tests" to "Platelet Function Tests",
        "Platelet-activating Factor Acetylhydrolase" to "Platelet-activating Factor Acetylhydrolase",
        "Pleural Fluid Testing" to "Pleural Fluid Testing",
        "Pleural Fluid Testing" to "Pleural Fluid Testing",
        "Potassium Hydroxide Preparation" to "Potassium Hydroxide Preparation",
        "Pregnancy Test (hCG)" to "Pregnancy Test (hCG)",
        "Pregnancy Test (hCG)" to "Pregnancy Test (hCG)",
        "Presenilin 1 Gene" to "Presenilin 1 Gene",
        "Protein C Activity" to "Protein C Activity",
        "Protein C Level" to "Protein C Level",
        "Protein S Activity" to "Protein S Activity",
        "Protein S Level" to "Protein S Level",
        "Proteinase 3 Antibodies" to "Proteinase 3 Antibodies",
        "Purified Protein Derivative" to "Purified Protein Derivative",
        "Pyridoxal phosphate (B6)" to "Pyridoxal phosphate (B6)",
        "Quadruple Marker Test" to "Quadruple Marker Test",
        "RBC Ab ID" to "RBC Ab ID",
        "RBC Antibody Screen" to "RBC Antibody Screen",
        "RBC G6PD test" to "RBC G6PD test",
        "Rapid Flu Test" to "Rapid Flu Test",
        "Rapid Plasma Reagin" to "Rapid Plasma Reagin",
        "Rapid Strep Test" to "Rapid Strep Test",
        "Red Cell Cholinesterase" to "Red Cell Cholinesterase",
        "Red Cell Indices" to "Red Cell Indices",
        "Red Cell Indices" to "Red Cell Indices",
        "Renal Calculus Analysis" to "Renal Calculus Analysis",
        "Renal Function Panel" to "Renal Function Panel",
        "Respiratory Pathogens Panel" to "Respiratory Pathogens Panel",
        "Respiratory Pathogens Panel" to "Respiratory Pathogens Panel",
        "Respiratory Virus Profile" to "Respiratory Virus Profile",
        "Reticulocyte Production Index" to "Reticulocyte Production Index",
        "Reticulocyte Production Index" to "Reticulocytes",
        "Reticulocyte Production Index" to "Reticulocytes",
        "Rheumatoid Factor (RF)" to "Rheumatoid Factor (RF)",
        "Rheumatoid Factor (RF)" to "Rheumatoid Factor (RF)",
        "SARS-CoV-2 antigen test" to "SARS-CoV-2 antigen test",
        "Seminal Fluid Analysis" to "Seminal Fluid Analysis",
        "Serine Protease 3" to "Serine Protease 3",
        "Serum Digoxin Level" to "Serum Digoxin Level",
        "Serum Glutamic-Oxaloacetic Transaminase" to "Serum Glutamic-Oxaloacetic Transaminase",
        "Serum Glutamic-Pyruvic Transaminase" to "Serum Glutamic-Pyruvic Transaminase",
        "Serum Iron-Binding Capacity" to "Serum Iron-Binding Capacity",
        "Serum Protein Electrophoresis" to "Serum Protein Electrophoresis",
        "Serum Transferrin Receptors" to "Serum Transferrin Receptors",
        "Sexually Transmitted Diseases" to "Sexually Transmitted Diseases",
        "Sickle Cell Anemia" to "Sickle Cell Anemia",
        "Sickle Cell Screen" to "Sickle Cell Screen",
        "Sickle Cell Tests" to "Sickle Cell Tests",
        "Sickle Cell Tests" to "Sickle Cell Tests",
        "Soluble Mesothelin-Related Peptides" to "Soluble Mesothelin-Related Peptides",
        "Soluble Mesothelin-Related Peptides" to "Soluble Mesothelin-Related Peptides",
        "Soluble Transferrin Receptor" to "Soluble Transferrin Receptor",
        "Soluble Transferrin Receptor" to "Soluble Transferrin Receptor",
        "Spinal Fluid Analysis" to "Spinal Fluid Analysis",
        "Sports Doping Tests" to "Sports Doping Tests",
        "Sputum Culture, Bacterial" to "Sputum Culture, Bacterial",
        "Sputum Culture, Bacterial" to "Sputum Culture, Bacterial",
        "Stool Occult Blood" to "Stool Occult Blood",
        "Strep Group B" to "Strep Group B",
        "Strep Throat Test" to "Strep Throat Test",
        "Strep Throat Test" to "Strep Throat Test",
        "Substance Abuse Testing" to "Substance Abuse Testing",
        "Sweat Chloride Test" to "Sweat Chloride Test",
        "Sweat Chloride Test" to "Sweat Chloride Test",
        "Syndromic Multiplex Panel" to "Syndromic Multiplex Panel",
        "Synovial Fluid Analysis" to "Synovial Fluid Analysis",
        "Synovial Fluid Analysis" to "Synovial Fluid Analysis",
        "T-cell Gene Clonality" to "T-cell Gene Clonality",
        "TB Skin Test" to "TB Skin Test",
        "TB Skin Test" to "TB Skin Test",
        "T-cell Gene Clonality" to "TCGR",
        "TCR Gene Rearrangement" to "TCGR",
        "TCR Gene Rearrangement" to "TCR Gene Rearrangement",
        "TNF Alpha Antibodies" to "TNF Alpha Antibodies",
        "TNF Biologics Testing" to "TNF Biologics Testing",
        "TSH Receptor Antibody" to "TSH Receptor Antibody",
        "Tartrate-resistant Acid Phosphatase" to "Tartrate-resistant Acid Phosphatase",
        "Testosterone-estrogen Binding Globulin" to "Testosterone-estrogen Binding Globulin",
        "Tetrahydrocannabinol (THC) testing " to "Tetrahydrocannabinol (THC) testing ",
        "Theophylline and Caffeine" to "Theophylline and Caffeine",
        "Theophylline and Caffeine" to "Theophylline and Caffeine",
        "Therapeutic Drug Monitoring" to "Therapeutic Drug Monitoring",
        "Therapeutic Drug Monitoring" to "Therapeutic Drug Monitoring",
        "Thiopurine methyltransferase (TPMT)" to "Thiopurine methyltransferase (TPMT)",
        "Thiopurine methyltransferase (TPMT)" to "Thiopurine methyltransferase (TPMT)",
        "Thrombin Clotting Time" to "Thrombin Clotting Time",
        "Thyroid Microsomal Antibody" to "Thyroid Microsomal Antibody",
        "Thyroid Peroxidase Antibody" to "Thyroid Peroxidase Antibody",
        "Thyroid Stimulating Immunoglobulin" to "Thyroid Stimulating Immunoglobulin",
        "Thyroid-stimulating Hormone (TSH)" to "Thyroid-stimulating Hormone (TSH)",
        "Thyroid-stimulating Hormone (TSH)" to "Thyroid-stimulating Hormone (TSH)",
        "Thyrotropin Receptor Antibodies" to "Thyrotropin Receptor Antibodies",
        "Total beta hCG" to "Total beta hCG",
        "Mast Cell Tryptase" to "Tryptase",
        "Mast Cell Tryptase" to "Tryptase",
        "Urea breath test" to "Urea breath test",
        "Urinary Stone Analysis" to "Urinary Stone Analysis",
        "Urinary Tract Infection" to "Urinary Tract Infection",
        "Urine Drug Testing" to "Urine Drug Testing",
        "Urine Protein Electrophoresis" to "Urine Protein Electrophoresis",
        "Urine Supersaturation Profile" to "Urine Supersaturation Profile",
        "Urine Total Protein" to "Urine Total Protein",
        "Urine Uric Acid" to "Urine Uric Acid",
        "Vaginitis and Vaginosis" to "Vaginitis and Vaginosis",
        "Vanillylmandelic Acid (VMA)" to "Vanillylmandelic Acid (VMA)",
        "Vanillylmandelic Acid (VMA)" to "Vanillylmandelic Acid (VMA)",
        "Viral Hepatitis Panel" to "Viral Hepatitis Panel",
        "Vitamin B complex" to "Vitamin B complex",
        "Vitamin D Tests" to "Vitamin D Tests",
        "Vitamin D Tests" to "Vitamin D Tests",
        "Vitamin K Deficiency" to "Vitamin K Deficiency",
        "WBC Count Differential" to "WBC Count Differential",
        "WNV by NAAT" to "WNV by NAAT",
        "Warfarin Sensitivity Testing" to "Warfarin Sensitivity Testing",
        "Warfarin Sensitivity Testing" to "Warfarin Sensitivity Testing",
        "West Nile Virus" to "West Nile Virus",
        "Westergren Sedimentation Rate" to "Westergren Sedimentation Rate",
        "Wintrobe Sedimentation Rate" to "Wintrobe Sedimentation Rate",
        "Xylose Absorption Test" to "Xylose Absorption Test",
        "Xylose Absorption Test" to "Xylose Absorption Test",
        "Xylose Tolerance Test" to "Xylose Tolerance Test",
        "Zika Antibody Test" to "Zika Antibody Test",
        "Zika RT-PCR Test" to "Zika RT-PCR Test",
        "Zika Virus Testing" to "Zika Virus Testing",
        "Zika Virus Testing" to "Zika Virus Testing",
        "hCG Tumor Marker" to "hCG Tumor Marker",
        "hCG Tumor Marker" to "hCG Tumor Marker",
        "von Willebrand Factor" to "von Willebrand Factor",
        "von Willebrand Factor" to "von Willebrand Factor"
    )

    val twoWords = hashMapOf(
        "17-OH Progesterone" to "17-Hydroxyprogesterone",
        "17-OH Progesterone" to "17-Hydroxyprogesterone",
        "17-OH Progesterone " to "17-OH Progesterone ",
        "25-hydroxyvitamin D" to "25-hydroxyvitamin D",
        "3-day Measles" to "3-day Measles",
        "4-marker Screen" to "4-marker Screen",
        "Serotonin Metabolite" to "5-HIAA",
        "Serotonin Metabolite" to "5-HIAA",
        "5-hydroxyindoleacetic Acid" to "5-hydroxyindoleacetic Acid",
        "A-G Ratio" to "A-G Ratio",
        "AChR Antibody" to "AChR Antibody",
        "AFP Maternal" to "AFP Maternal",
        "AIDS Screen" to "AIDS Screen",
        "AIDS Test" to "AIDS Test",
        "Anti-malignin antibody" to "AMAS",
        "Anti-malignin antibody" to "AMAS",
        "ANCA Antibodies" to "ANCA Antibodies",
        "APC Resistance" to "APC Resistance",
        "APOE e4 " to "APOE e4 ",
        "AT 3" to "AT 3",
        "AT III" to "AT III",
        "Acetoacetic Acid" to "Acetoacetic Acid",
        "Acetylsalicylic acid" to "Acetylsalicylic acid",
        "Actin Antibody" to "Actin Antibody",
        "Adenosine Deaminase" to "Adenosine Deaminase",
        "Adenosine Deaminase" to "Adenosine Deaminase",
        "Alanine Transaminase" to "Alanine Transaminase",
        "Albumin (urine)" to "Albumin (urine)",
        "Albumin-to-Creatinine Ratio" to "Albumin-to-Creatinine Ratio",
        "Albumin/Globulin Ratio" to "Albumin/Globulin Ratio",
        "Alcohol Dependence" to "Alcoholism",
        "Alk Phos" to "Alk Phos",
        "Allergy Screen" to "Allergy Screen",
        "Alloantibody Identification" to "Alloantibody Identification",
        "Alpha Tryptase" to "Alpha Tryptase",
        "Alpha-1 Antitrypsin" to "Alpha-1 Antitrypsin",
        "Alpha-1 Antitrypsin" to "Alpha-1 Antitrypsin",
        "Alpha-fetoprotein (Total)" to "Alpha-fetoprotein (Total)",
        "Alpha-fetoprotein-L3 Percent" to "Alpha-fetoprotein-L3 Percent",
        "Alzheimer Biomarkers" to "Alzheimer Biomarkers",
        "Alzheimer Disease" to "Alzheimer Disease",
        "Aminoglycoside Antibiotics" to "Aminoglycoside Antibiotics",
        "Aminoglycoside Antibiotics" to "Aminoglycoside Antibiotics",
        "About Anemia" to "Anemia",
        "Anion Gap" to "Anion Gap",
        "Ankylosing Spondylitis" to "Ankylosing Spondylitis",
        "Anti-DNase B" to "Anti-DNase B",
        "Anti-DNase B" to "Anti-DNase B",
        "Anti-Intrinsic Factor" to "Anti-Intrinsic Factor",
        "LKM1 Antibodies" to "Anti-LKM-1",
        "LKM1 Antibodies" to "Anti-LKM-1",
        "Anti-Müllerian Hormone" to "Anti-Müllerian Hormone",
        "Anti-Müllerian Hormone" to "Anti-Müllerian Hormone",
        "Anti-Sm (Sm)" to "Anti-Sm (Sm)",
        "Anti-TNF Inhibitor" to "Anti-TNF Inhibitor",
        "Anti-Xa chromogenic" to "Anti-Xa chromogenic",
        "Anti-citrulline Antibody" to "Anti-citrulline Antibody",
        "Antibody Screen" to "Antibody Screen",
        "Anticardiolipin Antibodies" to "Anticardiolipin Antibodies",
        "Anticentromere Antibody" to "Anticentromere Antibody",
        "Anticentromere Antibody" to "Anticentromere Antibody",
        "Anticytoplasmic Autoantibodies" to "Anticytoplasmic Autoantibodies",
        "Antimicrobial Susceptibility" to "Antimicrobial Susceptibility",
        "Antimicrosomal Antibody" to "Antimicrosomal Antibody",
        "Antiphospholipid Antibodies" to "Antiphospholipid Antibodies",
        "Antiphospholipid Antibodies" to "Antiphospholipid Antibodies",
        "Antiphospholipid Syndrome" to "Antiphospholipid Syndrome",
        "Antireticulin Antibodies" to "Antireticulin Antibodies",
        "AT III" to "Antithrombin",
        "AT 3" to "Antithrombin",
        "AT III" to "Antithrombin",
        "AT 3" to "Antithrombin",
        "Antithyroglobulin Antibody" to "Antithyroglobulin Antibody",
        "Antithyroid Antibodies" to "Antithyroid Antibodies",
        "Apo A" to "Apo A",
        "Apo A-I" to "Apo A-I",
        "Apo A-I" to "Apo A-I",
        "Apo B" to "Apo B",
        "Apo B" to "Apo B",
        "Apolipoprotein B-100" to "Apolipoprotein B-100",
        "Arbovirus Testing" to "Arbovirus Testing",
        "Arbovirus Testing" to "Arbovirus Testing",
        "Arginine Vasopressin" to "Arginine Vasopressin",
        "Aspartate Transaminase" to "Aspartate Transaminase",
        "Autoimmune antibodies" to "Autoantibodies",
        "Autoimmune antibodies" to "Autoantibodies",
        "Autoimmune Diseases" to "Autoimmune Diseases",
        "Autoimmune antibodies" to "Autoimmune antibodies",
        "B Vitamins" to "B Vitamins",
        "B Vitamins" to "B Vitamins",
        "Philadelphia Chromosome" to "BCR-ABL1",
        "Philadelphia Chromosome" to "BCR-ABL1",
        "Baby aspirin" to "Baby aspirin",
        "Beta Tryptase" to "Beta Tryptase",
        "Beta hCG" to "Beta hCG",
        "Beta-hydroxybutyric Acid" to "Beta-hydroxybutyric Acid",
        "Total Bilirubin" to "Bilirubin",
        "Neonatal Bilirubin" to "Bilirubin",
        "Direct Bilirubin" to "Bilirubin",
        "Conjugated Bilirubin" to "Bilirubin",
        "Indirect Bilirubin" to "Bilirubin",
        "Unconjugated Bilirubin" to "Bilirubin",
        "Total Bilirubin" to "Bilirubin",
        "Neonatal Bilirubin" to "Bilirubin",
        "Direct Bilirubin" to "Bilirubin",
        "Conjugated Bilirubin" to "Bilirubin",
        "Indirect Bilirubin" to "Bilirubin",
        "Unconjugated Bilirubin" to "Bilirubin",
        "Bioavailable Testosterone" to "Bioavailable Testosterone",
        "Bioterrorism Agents" to "Bioterrorism Agents",
        "Biotin (B7)" to "Biotin (B7)",
        "Bismuth subsalicylate" to "Bismuth subsalicylate",
        "Bleeding Disorders" to "Bleeding Disorders",
        "Blood Cholesterol" to "Blood Cholesterol",
        "Blood Copper" to "Blood Copper",
        "Blood Creatinine" to "Blood Creatinine",
        "Blood Culture" to "Blood Culture",
        "Blood Culture" to "Blood Culture",
        "Blood Differential" to "Blood Differential",
        "Blood Film" to "Blood Film",
        "Blood Gases" to "Blood Gases",
        "Blood Gases" to "Blood Gases",
        "Blood Group" to "Blood Group",
        "Blood Ketones" to "Blood Ketones",
        "Blood Ketones" to "Blood Ketones",
        "Blood Smear" to "Blood Smear",
        "Blood Smear" to "Blood Smear",
        "Blood Sugar" to "Blood Sugar",
        "Blood Typing" to "Blood Typing",
        "Blood Typing" to "Blood Typing",
        "Bone Markers" to "Bone Markers",
        "Bone Markers" to "Bone Markers",
        "Breast Cancer" to "Breast Cancer",
        "Insulin C-peptide" to "C-peptide",
        "Proinsulin C-peptide" to "C-peptide",
        "Insulin C-peptide" to "C-peptide",
        "Proinsulin C-peptide" to "C-peptide",
        "CA 15-3" to "CA 15-3",
        "CA 15-3" to "CA 15-3",
        "CA 19-9" to "CA 19-9",
        "CALR Mutation" to "CALR Mutation",
        "CALR Mutation" to "CALR Mutation",
        "CCP Antibody" to "CCP Antibody",
        "CD4 Count" to "CD4 Count",
        "CD4 Count" to "CD4 Count",
        "CD4 Percent" to "CD4 Percent",
        "CK MB" to "CK MB",
        "CK MB" to "CK-MB",
        "CPK MB" to "CK-MB",
        "CK MB" to "CK-MB",
        "CPK MB" to "CK-MB",
        "CLO test" to "CLO test",
        "CO2 Content" to "CO2 Content",
        "COVID-19 RT-PCR" to "COVID-19 RT-PCR",
        "CPK MB" to "CPK MB",
        "CSF Analysis" to "CSF Analysis",
        "CSF Lactate" to "CSF Lactate",
        "CYP2C19 Genotype" to "CYP2C19 Genotype",
        "CYP2C9 Genotype" to "CYP2C9 Genotype",
        "Human Calcitonin" to "Calcitonin",
        "Human Calcitonin" to "Calcitonin",
        "Total Calcium" to "Calcium",
        "Ionized Calcium" to "Calcium",
        "Total Calcium" to "Calcium",
        "Ionized Calcium" to "Calcium",
        "Fecal Calprotectin" to "Calprotectin",
        "Stool Calprotectin" to "Calprotectin",
        "Fecal Calprotectin" to "Calprotectin",
        "Stool Calprotectin" to "Calprotectin",
        "Cancer Antigen-Breast" to "Cancer Antigen-Breast",
        "Cancer Antigen-GI" to "Cancer Antigen-GI",
        "Capillary Electrophoresis" to "Capillary Electrophoresis",
        "Total Carbamazepine" to "Carbamazepine",
        "Total Carbamazepine" to "Carbamazepine",
        "Cardiac Biomarkers" to "Cardiac Biomarkers",
        "Cardiac Biomarkers" to "Cardiac Biomarkers",
        "Cardiac CRP" to "Cardiac CRP",
        "Cardiac Fibrinogen" to "Cardiac Fibrinogen",
        "Cardiac Markers" to "Cardiac Markers",
        "Cardiolipin Antibodies" to "Cardiolipin Antibodies",
        "Cardiolipin Antibodies" to "Cardiolipin Antibodies",
        "Fractionated Catecholamines" to "Catecholamines",
        "Fractionated Catecholamines" to "Catecholamines",
        "Celiac Disease" to "Celiac Disease",
        "Centromere Antibody" to "Centromere Antibody",
        "Ceruloplasmin, serum" to "Ceruloplasmin",
        "Ceruloplasmin, serum" to "Ceruloplasmin",
        "Cervical Cancer" to "Cervical Cancer",
        "Cervical Cytology" to "Cervical Cytology",
        "Cervical Smear" to "Cervical Smear",
        "Chem 14" to "Chem 14",
        "Chem 7" to "Chem 7",
        "Chemistry 14" to "Chemistry 14",
        "Chemistry Panel" to "Chemistry Panel",
        "Chemistry Panels" to "Chemistry Panels",
        "Chemistry Panels" to "Chemistry Panels",
        "Chemistry Screen" to "Chemistry Screen",
        "Chlamydia Culture" to "Chlamydia Culture",
        "Chlamydia Testing" to "Chlamydia Testing",
        "Chlamydia Testing" to "Chlamydia Testing",
        "Blood Cholesterol" to "Cholesterol",
        "Blood Cholesterol" to "Cholesterol",
        "Cholesterol Panel" to "Cholesterol Panel",
        "Choline salicylate" to "Choline salicylate",
        "Cholinesterase Tests" to "Cholinesterase Tests",
        "Cholinesterase Tests" to "Cholinesterase Tests",
        "Chromogranin A" to "Chromogranin A",
        "Chromogranin A" to "Chromogranin A",
        "Chromosome Karyotype" to "Chromosome Karyotype",
        "Chromosome Studies" to "Chromosome Studies",
        "Chymotrypsin, fecal" to "Chymotrypsin",
        "Chymotrypsin, fecal" to "Chymotrypsin",
        "Chymotrypsin, fecal" to "Chymotrypsin, fecal",
        "Citrulline Antibody" to "Citrulline Antibody",
        "Clotting Factors" to "Clotting Factors",
        "Coagulation Cascade" to "Coagulation Cascade",
        "Coagulation Cascade" to "Coagulation Cascade",
        "Coagulation Factors" to "Coagulation Factors",
        "Coagulation Factors" to "Coagulation Factors",
        "Cold Agglutinins" to "Cold Agglutinins",
        "Cold Agglutinins" to "Cold Agglutinins",
        "Cold Autoantibodies" to "Cold Autoantibodies",
        "Cold-Reacting Antibodies" to "Cold-Reacting Antibodies",
        "Colon Cancer" to "Colon Cancer",
        "Total Complement" to "Complement",
        "Total Complement" to "Complement",
        "Conjugated Bilirubin" to "Conjugated Bilirubin",
        "Urine Copper" to "Copper",
        "Blood Copper" to "Copper",
        "Free Copper" to "Copper",
        "Hepatic Copper" to "Copper",
        "Urine Copper" to "Copper",
        "Blood Copper" to "Copper",
        "Free Copper" to "Copper",
        "Hepatic Copper" to "Copper",
        "Corrected Reticulocyte" to "Corrected Reticulocyte",
        "Corticotropin test" to "Corticotropin test",
        "Urinary Cortisol" to "Cortisol",
        "Salivary Cortisol" to "Cortisol",
        "Free Cortisol" to "Cortisol",
        "Urinary Cortisol" to "Cortisol",
        "Salivary Cortisol" to "Cortisol",
        "Free Cortisol" to "Cortisol",
        "Creatine Phosphokinase" to "Creatine Phosphokinase",
        "Blood Creatinine" to "Creatinine",
        "Serum Creatinine" to "Creatinine",
        "Urine Creatinine" to "Creatinine",
        "Blood Creatinine" to "Creatinine",
        "Serum Creatinine" to "Creatinine",
        "Urine Creatinine" to "Creatinine",
        "Culture, Throat" to "Culture, Throat",
        "Cushing Syndrome" to "Cushing Syndrome",
        "Common Questions" to "Cyclosporine",
        "Common Questions" to "Cyclosporine",
        "Cystatin C" to "Cystatin C",
        "Cystatin C" to "Cystatin C",
        "Cystic Fibrosis" to "Cystic Fibrosis",
        "Cytogenetic Analysis" to "Cytogenetic Analysis",
        "Fragment D-dimer" to "D-dimer",
        "Fragment D-dimer" to "D-dimer",
        "DHEA Sulfate" to "DHEA Sulfate",
        "DHEA Sulfate" to "DHEAS",
        "DHEA Sulfate" to "DHEAS",
        "Darkfield Microscopy" to "Darkfield Microscopy",
        "Delta-aminolevulinic Acid" to "Delta-aminolevulinic Acid",
        "Diabetes Autoantibodies" to "Diabetes Autoantibodies",
        "Differential Slide" to "Differential Slide",
        "Direct Bilirubin" to "Direct Bilirubin",
        "Direct LDL" to "Direct LDL",
        "Direct LDL-C" to "Direct LDL-C",
        "Down Syndrome" to "Down Syndrome",
        "Drug Screen" to "Drug Screen",
        "Drug Test" to "Drug Test",
        "Drug Testing" to "Drug Testing",
        "E. coli" to "E. coli",
        "EBV Antibodies" to "EBV Antibodies",
        "ENA Panel" to "ENA Panel",
        "Elastase, stool" to "Elastase, stool",
        "Protein ELP" to "Electrophoresis",
        "Gel Electrophoresis" to "Electrophoresis",
        "Capillary Electrophoresis" to "Electrophoresis",
        "Immunosubtraction Electrophoresis" to "Electrophoresis",
        "Endomysial Antibody" to "Endomysial Antibody",
        "Erythrocyte Acetylcholinesterase" to "Erythrocyte Acetylcholinesterase",
        "Erythrocyte Count" to "Erythrocyte Count",
        "Erythrocyte Morphology" to "Erythrocyte Morphology",
        "Essential Minerals" to "Essential Minerals",
        "Estimated GFR" to "Estimated GFR",
        "Estradiol (E2)" to "Estradiol (E2)",
        "Estriol (E3)" to "Estriol (E3)",
        "Estrogen Fractions/fractionated" to "Estrogen Fractions/fractionated",
        "Estrogen Receptors" to "Estrogen Receptors",
        "Estrogenic Hormones" to "Estrogenic Hormones",
        "Estrogen Fractions/fractionated" to "Estrogens",
        "Estrone (E1)" to "Estrogens",
        "Estradiol (E2)" to "Estrogens",
        "Estriol (E3)" to "Estrogens",
        "Estrogenic Hormones" to "Estrogens",
        "Estrogen Fractions/fractionated" to "Estrogens",
        "Estrone (E1)" to "Estrogens",
        "Estradiol (E2)" to "Estrogens",
        "Estriol (E3)" to "Estrogens",
        "Estrogenic Hormones" to "Estrogens",
        "Estrone (E1)" to "Estrone (E1)",
        "Ethyl Alcohol" to "Ethanol",
        "Ethyl Alcohol" to "Ethanol",
        "Ethyl Alcohol" to "Ethyl Alcohol",
        "F-Actin Antibody" to "F-Actin Antibody",
        "FMR1 Testing" to "FMR1 Testing",
        "Factor Assays" to "Factor Assays",
        "Factor I" to "Factor I",
        "Factor II" to "Factor II",
        "Factor IX" to "Factor IX",
        "Factor V" to "Factor V",
        "Factor VII" to "Factor VII",
        "Factor VIII" to "Factor VIII",
        "Factor X" to "Factor X",
        "Factor XI" to "Factor XI",
        "Factor XIII" to "Factor XIII",
        "Fasting Insulin" to "Fasting Insulin",
        "Fat, Feces" to "Fat, Feces",
        "Fe Tests" to "Fe Tests",
        "Fecal Calprotectin" to "Fecal Calprotectin",
        "Fecal Fat" to "Fecal Fat",
        "Fecal Fat" to "Fecal Fat",
        "Fecal Lactoferrin" to "Fecal Lactoferrin",
        "Feces Culture" to "Feces Culture",
        "Serum Ferritin" to "Ferritin",
        "Serum Ferritin" to "Ferritin",
        "Fibrinogen Antigen" to "Fibrinogen",
        "Cardiac Fibrinogen" to "Fibrinogen",
        "Fibrinogen Antigen" to "Fibrinogen",
        "Cardiac Fibrinogen" to "Fibrinogen",
        "Fibrinogen Antigen" to "Fibrinogen Antigen",
        "Flow Cytometry" to "Flow Cytometry",
        "Flu Test" to "Flu Test",
        "Folic Acid" to "Folic Acid",
        "Fractionated Catecholamines" to "Fractionated Catecholamines",
        "Fractionated Metanephrines" to "Fractionated Metanephrines",
        "Fragment D-dimer" to "Fragment D-dimer",
        "Free Copper" to "Free Copper",
        "Free Cortisol" to "Free Cortisol",
        "Free PSA" to "Free PSA",
        "Free Testosterone" to "Free Testosterone",
        "Free Triiodothyronine" to "Free Triiodothyronine",
        "Fungal Infections" to "Fungal Infections",
        "Fungal Tests" to "Fungal Tests",
        "Fungal Tests" to "Fungal Tests",
        "GAD65 Autoantibodies" to "GAD65 Autoantibodies",
        "GC Test" to "GC Test",
        "GI Panel" to "GI Panel",
        "Gamma-Glutamyl Transpeptidase" to "Gamma-Glutamyl Transpeptidase",
        "Common Questions" to "Gastrin",
        "Common Questions" to "Gastrin",
        "Gel Electrophoresis" to "Gel Electrophoresis",
        "German Measles" to "German Measles",
        "Glucose Tests" to "Glucose Tests",
        "Glucose Tests" to "Glucose Tests",
        "Glucose-6-Phosphate Dehydrogenase" to "Glucose-6-Phosphate Dehydrogenase",
        "Glycated Hemoglobin" to "Glycated Hemoglobin",
        "Glycosylated Hemoglobin" to "Glycosylated Hemoglobin",
        "Gonorrhea Testing" to "Gonorrhea Testing",
        "Gonorrhea Testing" to "Gonorrhea Testing",
        "Gram Stain" to "Gram Stain",
        "Gram Stain" to "Gram Stain",
        "Gram\"s Stain" to "Gram\"s Stain",
        "Graves Disease" to "Graves Disease",
        "Growth Hormone" to "Growth Hormone",
        "Growth Hormone" to "Growth Hormone",
        "Guaiac-based FOBT" to "Guaiac-based FOBT",
        "Guillain-Barré Syndrome" to "Guillain-Barré Syndrome",
        "HAV-Ab IgG" to "HAV-Ab IgG",
        "HAV-Ab IgM" to "HAV-Ab IgM",
        "HAV-Ab total" to "HAV-Ab total",
        "HBV DNA" to "HBV DNA",
        "HBV Tests" to "HBV Tests",
        "HDL Cholesterol" to "HDL Cholesterol",
        "HDL Cholesterol" to "HDL Cholesterol",
        "HIT Antibody" to "HIT Antibody",
        "HIV Serology" to "HIV Serology",
        "HIV Tests" to "HIV Tests",
        "HIV Tests" to "HIV Tests",
        "HLA Crossmatching" to "HLA Crossmatching",
        "HLA Testing" to "HLA Testing",
        "HLA Testing" to "HLA Testing",
        "HLA-B27 Antigen" to "HLA-B27",
        "HLA-B27 Antigen" to "HLA-B27",
        "HLA-B27 Antigen" to "HLA-B27 Antigen",
        "HPV DNA" to "HPV DNA",
        "HPV mRNA" to "HPV mRNA",
        "HSV DNA" to "HSV DNA",
        "HSV-1 IgG" to "HSV-1 IgG",
        "HSV-2 IgG" to "HSV-2 IgG",
        "HTLV-I/II Antibodies" to "HTLV-I/II Antibodies",
        "Hemoglobin-binding Protein" to "Haptoglobin",
        "Hemoglobin-binding Protein" to "Haptoglobin",
        "Hashimoto Thyroiditis" to "Hashimoto Thyroiditis",
        "Hb ELP" to "Hb ELP",
        "Hb IEF" to "Hb IEF",
        "Hb S" to "Hb S",
        "Heart Disease" to "Heart Disease",
        "Heavy Metals" to "Heavy Metals",
        "Heavy Metals" to "Heavy Metals",
        "Hemoglobin A1c" to "Hemoglobin A1c",
        "Hemoglobin A1c" to "Hemoglobin A1c",
        "Hemoglobin Abnormalities" to "Hemoglobin Abnormalities",
        "Hemoglobin Evaluation" to "Hemoglobin Evaluation",
        "Hemoglobin Fractionation" to "Hemoglobin Fractionation",
        "Hemoglobin S" to "Hemoglobin S",
        "Hemoglobin-binding Protein" to "Hemoglobin-binding Protein",
        "Hemoglobinopathy Evaluation" to "Hemoglobinopathy Evaluation",
        "Hemoglobinopathy Evaluation" to "Hemoglobinopathy Evaluation",
        "Hep B" to "Hep B",
        "Heparin Activity" to "Heparin Activity",
        "Heparin Anti-Xa" to "Heparin Anti-Xa",
        "Heparin Anti-Xa" to "Heparin Anti-Xa",
        "Heparin Level" to "Heparin Level",
        "Heparin-PF4 Antibody" to "Heparin-PF4 Antibody",
        "Hepatic Copper" to "Hepatic Copper",
        "Hepatitis Panel" to "Hepatitis Panel",
        "Herpes Culture" to "Herpes Culture",
        "Herpes Testing" to "Herpes Testing",
        "Herpes Testing" to "Herpes Testing",
        "Herpes Zoster" to "Herpes Zoster",
        "Hgb S" to "Hgb S",
        "High-risk HPV" to "High-risk HPV",
        "Common Questions" to "Histamine",
        "Common Questions" to "Histamine",
        "Histocompatibility Testing" to "Histocompatibility Testing",
        "Histone Antibody" to "Histone Antibody",
        "Histone Antibody" to "Histone Antibody",
        "Histone Autoantibodies" to "Histone Autoantibodies",
        "Urine Homocysteine" to "Homocysteine",
        "Urine Homocysteine" to "Homocysteine",
        "Human Calcitonin" to "Human Calcitonin",
        "Huntington Disease" to "Huntington Disease",
        "IF Antibody" to "IF Antibody",
        "Immunofixation Electrophoresis" to "Immunofixation Electrophoresis",
        "Immunoglobulin A" to "Immunoglobulin A",
        "Immunoglobulin G" to "Immunoglobulin G",
        "Immunoglobulin M" to "Immunoglobulin M",
        "Immunoreactive Trypsin" to "Immunoreactive Trypsin",
        "Immunosubtraction Electrophoresis" to "Immunosubtraction Electrophoresis",
        "Indirect Bilirubin" to "Indirect Bilirubin",
        "Influenza Tests" to "Influenza Tests",
        "Influenza Tests" to "Influenza Tests",
        "Fasting Insulin" to "Insulin",
        "Fasting Insulin" to "Insulin",
        "Insulin C-peptide" to "Insulin C-peptide",
        "Insulin Resistance" to "Insulin Resistance",
        "Intact PTH" to "Intact PTH",
        "Intact hCG" to "Intact hCG",
        "Ionized Calcium" to "Ionized Calcium",
        "Serum Iron" to "Iron",
        "Serum Fe" to "Iron",
        "Serum Iron" to "Iron",
        "Serum Fe" to "Iron",
        "Iron Indices" to "Iron Indices",
        "Iron Tests" to "Iron Tests",
        "Iron Tests" to "Iron Tests",
        "JAK2 Mutation" to "JAK2 Mutation",
        "JAK2 Mutation" to "JAK2 Mutation",
        "JAK2 V617F" to "JAK2 V617F",
        "KOH Prep" to "KOH Prep",
        "KRAS Mutation" to "KRAS Mutation",
        "KRAS Mutation" to "KRAS Mutation",
        "Ketone Bodies" to "Ketone Bodies",
        "Kidney Disease" to "Kidney Disease",
        "Kidney Panel" to "Kidney Panel",
        "LDL Cholesterol" to "LDL Cholesterol",
        "LDL Cholesterol" to "LDL Cholesterol",
        "LDL D" to "LDL D",
        "LKM1 Antibodies" to "LKM1 Antibodies",
        "Lactic Acid" to "Lactate",
        "CSF Lactate" to "Lactate",
        "Lactic Acid" to "Lactate",
        "CSF Lactate" to "Lactate",
        "Lactic Acid" to "Lactic Acid",
        "Fecal Lactoferrin" to "Lactoferrin",
        "Stool Lactoferrin" to "Lactoferrin",
        "Fecal Lactoferrin" to "Lactoferrin",
        "Stool Lactoferrin" to "Lactoferrin",
        "Lactose Intolerance" to "Lactose Intolerance",
        "Lead Poisoning" to "Lead Poisoning",
        "Legionella Testing" to "Legionella Testing",
        "Legionella Testing" to "Legionella Testing",
        "Legionella pneumophila" to "Legionella pneumophila",
        "Common Questions" to "Leptin",
        "Common Questions" to "Leptin",
        "Leukocyte Count" to "Leukocyte Count",
        "Leukocyte Differential" to "Leukocyte Differential",
        "Common Questions" to "Levetiracetam",
        "Common Questions" to "Levetiracetam",
        "Lipid Panel" to "Lipid Panel",
        "Lipid Panel" to "Lipid Panel",
        "Lipid Profile" to "Lipid Profile",
        "Cholesterol Panel" to "Lipid Profile",
        "Lipid Test" to "Lipid Profile",
        "Lipid Test" to "Lipid Test",
        "Lipoprotein (a) " to "Lipoprotein (a) ",
        "Lipoprotein (a) " to "Lipoprotein (a) ",
        "Liquid Biopsy" to "Liquid Biopsy",
        "Liquid Biopsy" to "Liquid Biopsy",
        "Common Questions" to "Lithium",
        "Common Questions" to "Lithium",
        "Liver Cancer" to "Liver Cancer",
        "Hepatic Disease" to "Liver Disease",
        "Liver Panel" to "Liver Panel",
        "Liver Panel" to "Liver Panel",
        "Liver Profile" to "Liver Profile",
        "Low Platelets" to "Low Platelets",
        "Lung Cancer" to "Lung Cancer",
        "Lung Diseases" to "Lung Diseases",
        "Lupus Inhibitor" to "Lupus",
        "Lupus Inhibitor" to "Lupus Inhibitor",
        "Lyme Disease" to "Lyme Disease",
        "Lynch Syndrome" to "Lynch Syndrome",
        "MRSA Screening" to "MRSA Screening",
        "MRSA Screening" to "MRSA Screening",
        "MTHFR Mutation" to "MTHFR Mutation",
        "MTHFR Mutation" to "MTHFR Mutation",
        "Magnesium salicylate" to "Magnesium salicylate",
        "Manual Differential" to "Manual Differential",
        "Mature Tryptase" to "Mature Tryptase",
        "Metabolic Syndrome" to "Metabolic Syndrome",
        "Methyl salicylate" to "Methyl salicylate",
        "Methylmalonic Acid" to "Methylmalonic Acid",
        "Methylmalonic Acid" to "Methylmalonic Acid",
        "Microhemagglutination Assay" to "Microhemagglutination Assay",
        "Mitochondrial Antibody" to "Mitochondrial Antibody",
        "MuSK Autoantibody" to "MuSK Autoantibody",
        "Multiple Myeloma" to "Multiple Myeloma",
        "Multiple Sclerosis" to "Multiple Sclerosis",
        "Myasthenia Gravis" to "Myasthenia Gravis",
        "Mycology Tests" to "Mycology Tests",
        "Mycophenolate Mofetil" to "Mycophenolate Mofetil",
        "Mycophenolate Sodium" to "Mycophenolate Sodium",
        "Mycophenolic Acid" to "Mycophenolic Acid",
        "Mycophenolic Acid" to "Mycophenolic Acid",
        "Mycoplasma Culture" to "Mycoplasma",
        "Ureaplasma Culture" to "Mycoplasma",
        "Mycoplasma Culture" to "Mycoplasma",
        "Ureaplasma Culture" to "Mycoplasma",
        "Mycoplasma Culture" to "Mycoplasma Culture",
        "Myelodysplastic Syndrome" to "Myelodysplastic Syndrome",
        "Myeloperoxidase Antibodies" to "Myeloperoxidase Antibodies",
        "Myeloproliferative Neoplasms" to "Myeloproliferative Neoplasms",
        "Urine Myoglobin" to "Myoglobin",
        "Serum Myoglobin" to "Myoglobin",
        "Urine Myoglobin" to "Myoglobin",
        "Serum Myoglobin" to "Myoglobin",
        "Müllerian-Inhibiting Substance" to "Müllerian-Inhibiting Substance",
        "Müllerian-inhibiting Hormone" to "Müllerian-inhibiting Hormone",
        "Natriuretic Peptides" to "Natriuretic Peptides",
        "Neonatal Bilirubin" to "Neonatal Bilirubin",
        "Newborn Screening" to "Newborn Screening",
        "Niacin (B3)" to "Niacin (B3)",
        "Opioid Testing" to "Opioid Testing",
        "Opioid Testing" to "Opioid Testing",
        "Osmotic Gap" to "Osmotic Gap",
        "Ovarian Cancer" to "Ovarian Cancer",
        "PML-RARA t(15;17)(q22;q12)" to "PML-RARA",
        "PML-RARA t(15;17)(q22;q12)" to "PML-RARA",
        "PML-RARA t(15;17)(q22;q12)" to "PML-RARA t(15;17)(q22;q12)",
        "PT G20210A" to "PT G20210A",
        "Pancreatic Cancer" to "Pancreatic Cancer",
        "Pancreatic Diseases" to "Pancreatic Diseases",
        "Pancreatic Elastase" to "Pancreatic Elastase",
        "Pancreatic Insufficiency" to "Pancreatic Insufficiency",
        "Parathyroid Diseases" to "Parathyroid Diseases",
        "Parvo B19" to "Parvo B19",
        "Parvovirus B19" to "Parvovirus B19",
        "Parvovirus B19" to "Parvovirus B19",
        "Peptic Ulcer" to "Peptic Ulcer",
        "Peripheral Differential" to "Peripheral Differential",
        "Peripheral Smear" to "Peripheral Smear",
        "Pertussis Tests" to "Pertussis Tests",
        "Pharmacogenetic Tests" to "Pharmacogenetic Tests",
        "Pharmacogenetic Tests" to "Pharmacogenetic Tests",
        "Philadelphia Chromosome" to "Philadelphia Chromosome",
        "Phospholipid Antibodies" to "Phospholipid Antibodies",
        "Pituitary Disorders" to "Pituitary Disorders",
        "Plasma Cholinesterase" to "Plasma Cholinesterase",
        "Plasma Ketones" to "Plasma Ketones",
        "Plasma Metanephrines" to "Plasma Metanephrines",
        "Plasma Osmolality" to "Plasma Osmolality",
        "Platelet Count" to "Platelet Count",
        "Platelet Count" to "Platelet Count",
        "Poison Testing" to "Poison Testing",
        "Porphyrin Tests" to "Porphyrin Tests",
        "Porphyrin Tests" to "Porphyrin Tests",
        "Thyroxine-binding Prealbumin" to "Prealbumin",
        "Thyroxine-binding Prealbumin" to "Prealbumin",
        "Pregnancy: Preconception" to "Pregnancy: Preconception",
        "Common Questions" to "Pregnenolone",
        "Common Questions" to "Pregnenolone",
        "Pro Time" to "Pro Time",
        "Progesterone Receptors" to "Progesterone Receptors",
        "Proinsulin C-peptide" to "Proinsulin C-peptide",
        "Prostate Cancer" to "Prostate Cancer",
        "Protein ELP" to "Protein ELP",
        "Protein Electrophoresis" to "Protein Electrophoresis",
        "Pyridinium Crosslinks" to "Pyridinium Crosslinks",
        "Quad Screen" to "Quad Screen",
        "Qualitative hCG" to "Qualitative hCG",
        "Quantitative IgE" to "Quantitative IgE",
        "Quantitative hCG" to "Quantitative hCG",
        "RBC Cholinesterase" to "RBC Cholinesterase",
        "RBC Count" to "RBC Count",
        "RBC Folate" to "RBC Folate",
        "RP Panel" to "RP Panel",
        "Reactive Arthritis" to "Reactive Arthritis",
        "Real-time CGM" to "Real-time CGM",
        "Red Count" to "Red Count",
        "Renal Panel" to "Renal Panel",
        "Renal Panel" to "Renal Panel",
        "Respiratory Culture" to "Respiratory Culture",
        "Retic Count" to "Retic Count",
        "Reticulocyte Count" to "Reticulocyte Count",
        "Reticulocyte Index" to "Reticulocyte Index",
        "Reticulocyte Percent" to "Reticulocyte Percent",
        "Retic Count" to "Reticulocytes",
        "Reticulocyte Percent" to "Reticulocytes",
        "Reticulocyte Index" to "Reticulocytes",
        "Corrected Reticulocyte" to "Reticulocytes",
        "Retic Count" to "Reticulocytes",
        "Reticulocyte Percent" to "Reticulocytes",
        "Reticulocyte Index" to "Reticulocytes",
        "Corrected Reticulocyte" to "Reticulocytes",
        "Rh Factor" to "Rh Factor",
        "Rheumatoid Arthritis" to "Rheumatoid Arthritis",
        "Riboflavin (B2)" to "Riboflavin (B2)",
        "Ristocetin Cofactor" to "Ristocetin Cofactor",
        "Rubella Test" to "Rubella Test",
        "Rubella Test" to "Rubella Test",
        "SARS-CoV-2 Test" to "SARS-CoV-2 Test",
        "SSA (Ro)" to "SSA (Ro)",
        "SSB (La)" to "SSB (La)",
        "Salicylates (Aspirin)" to "Salicylates (Aspirin)",
        "Salicylates (Aspirin)" to "Salicylates (Aspirin)",
        "Salivary Cortisol" to "Salivary Cortisol",
        "Scleroderma Antibodies" to "Scleroderma Antibodies",
        "Sed Rate" to "Sed Rate",
        "Sedimentation Rate" to "Sedimentation Rate",
        "Semen Analysis" to "Semen Analysis",
        "Semen Analysis" to "Semen Analysis",
        "Sensitivity Testing" to "Sensitivity Testing",
        "Septic Arthritis" to "Septic Arthritis",
        "Serotonin Metabolite" to "Serotonin Metabolite",
        "Serum Creatinine" to "Serum Creatinine",
        "Serum Fe" to "Serum Fe",
        "Serum Ferritin" to "Serum Ferritin",
        "Serum Iron" to "Serum Iron",
        "Serum Ketones" to "Serum Ketones",
        "Serum Myoglobin" to "Serum Myoglobin",
        "Serum Osmolality" to "Serum Osmolality",
        "Serum Trypsinogen" to "Serum Trypsinogen",
        "Serum Urate" to "Serum Urate",
        "Sjögren Syndrome" to "Sjögren Syndrome",
        "Smith Antibody" to "Smith Antibody",
        "Sodium salicylate" to "Sodium salicylate",
        "Somatomedin C" to "Somatomedin C",
        "Sperm Analysis" to "Sperm Analysis",
        "Sperm Count" to "Sperm Count",
        "Stool Calprotectin" to "Stool Calprotectin",
        "Stool Culture" to "Stool Culture",
        "Stool Culture" to "Stool Culture",
        "Stool DNA" to "Stool DNA",
        "Stool DNA" to "Stool DNA",
        "Stool Elastase" to "Stool Elastase",
        "Stool Elastase" to "Stool Elastase",
        "Stool Lactoferrin" to "Stool Lactoferrin",
        "Stool Lipids" to "Stool Lipids",
        "Streptococcal Screen" to "Streptococcal Screen",
        "Streptococcus agalactiae" to "Streptococcus agalactiae",
        "Sweat Electrolytes" to "Sweat Electrolytes",
        "Syphilis Tests" to "Syphilis Tests",
        "Syphilis Tests" to "Syphilis Tests",
        "T-helper Cells" to "T-helper Cells",
        "T. gondii" to "T. gondii",
        "T. vaginalis" to "T. vaginalis",
        "T4 Count" to "T4 Count",
        "T4, Free" to "T4, Free",
        "T4, Free" to "T4, Free",
        "TB NAAT" to "TB NAAT",
        "TORCH Panel" to "TORCH",
        "TORCH Panel" to "TORCH",
        "TORCH Panel" to "TORCH Panel",
        "TPMT Genotype" to "TPMT Genotype",
        "TPMT Phenotype" to "TPMT Phenotype",
        "TPMT RBC" to "TPMT RBC",
        "Testicular Cancer" to "Testicular Cancer",
        "Total Testosterone" to "Testosterone",
        "Free Testosterone" to "Testosterone",
        "Bioavailable Testosterone" to "Testosterone",
        "Total Testosterone" to "Testosterone",
        "Free Testosterone" to "Testosterone",
        "Bioavailable Testosterone" to "Testosterone",
        "Three-day Measles" to "Three-day Measles",
        "Throat Culture" to "Throat Culture",
        "Thrombin Time" to "Thrombin Time",
        "Thrombin Time" to "Thrombin Time",
        "Thrombocyte Count" to "Thrombocyte Count",
        "Thyroid Antibodies" to "Thyroid Antibodies",
        "Thyroid Antibodies" to "Thyroid Antibodies",
        "Thyroid Autoantibodies" to "Thyroid Autoantibodies",
        "Thyroid Cancer" to "Thyroid Cancer",
        "Thyroid Diseases" to "Thyroid Diseases",
        "Thyroid Nodules" to "Thyroid Nodules",
        "Thyroid Panel" to "Thyroid Panel",
        "Thyroid Panel" to "Thyroid Panel",
        "Thyroperoxidase Antibody" to "Thyroperoxidase Antibody",
        "Thyroxine-binding Prealbumin" to "Thyroxine-binding Prealbumin",
        "Tissue Typing" to "Tissue Typing",
        "Total AFP" to "Total AFP",
        "Total Bilirubin" to "Total Bilirubin",
        "Total CK" to "Total CK",
        "Total CO2" to "Total CO2",
        "Total Calcium" to "Total Calcium",
        "Total Complement" to "Total Complement",
        "Total IgE" to "Total IgE",
        "Total IgE" to "Total IgE",
        "Total Immunoglobulins" to "Total Immunoglobulins",
        "Total PSA" to "Total PSA",
        "Total Testosterone" to "Total Testosterone",
        "Total Triiodothyronine" to "Total Triiodothyronine",
        "Total hCG" to "Total hCG",
        "Tox Screen" to "Tox Screen",
        "Toxic Metals" to "Toxic Metals",
        "Toxicology Assays" to "Toxicology Assays",
        "Toxicology Screen" to "Toxicology Screen",
        "Toxoplasma gondii" to "Toxoplasma gondii",
        "Toxoplasmosis Testing" to "Toxoplasmosis Testing",
        "Toxoplasmosis Testing" to "Toxoplasmosis Testing",
        "Trace Elements" to "Trace Elements",
        "Trace Minerals" to "Trace Minerals",
        "Trace Minerals" to "Trace Minerals",
        "Transferrin Receptor" to "Transferrin Receptor",
        "Transferrin Saturation" to "Transferrin Saturation",
        "Travelers\" Diseases" to "Travelers\" Diseases",
        "Trichomonas Testing" to "Trichomonas Testing",
        "Trichomonas Testing" to "Trichomonas Testing",
        "Triple Screen" to "Triple Screen",
        "Triple Test" to "Triple Test",
        "high-sensitivity troponin" to "Troponin",
        "high-sensitivity troponin" to "Troponin",
        "Trypsin-like Immunoreactivity" to "Trypsin-like Immunoreactivity",
        "Alpha Tryptase" to "Tryptase",
        "Beta Tryptase" to "Tryptase",
        "Mature Tryptase" to "Tryptase",
        "Alpha Tryptase" to "Tryptase",
        "Beta Tryptase" to "Tryptase",
        "Mature Tryptase" to "Tryptase",
        "Tumor Markers" to "Tumor Markers",
        "Tumor Markers" to "Tumor Markers",
        "Unconjugated Bilirubin" to "Unconjugated Bilirubin",
        "Urea Nitrogen" to "Urea Nitrogen",
        "Ureaplasma Culture" to "Ureaplasma Culture",
        "Uric Acid" to "Uric Acid",
        "Uric Acid" to "Uric Acid",
        "Urine Test" to "Urinalysis",
        "Urine Analysis" to "Urinalysis",
        "Urine Test" to "Urinalysis",
        "Urine Analysis" to "Urinalysis",
        "Urinary Cortisol" to "Urinary Cortisol",
        "Urine Analysis" to "Urine Analysis",
        "Urine Calcium" to "Urine Calcium",
        "Urine Copper" to "Urine Copper",
        "Urine Creatinine" to "Urine Creatinine",
        "Urine Culture" to "Urine Culture",
        "Urine Culture" to "Urine Culture",
        "Urine Homocysteine" to "Urine Homocysteine",
        "Urine Metanephrines" to "Urine Metanephrines",
        "Urine Metanephrines" to "Urine Metanephrines",
        "Urine Myoglobin" to "Urine Myoglobin",
        "Urine Osmolality" to "Urine Osmolality",
        "Urine Oxalate" to "Urine Oxalate",
        "Urine Test" to "Urine Test",
        "VKORC1 Genotype" to "VKORC1 Genotype",
        "VLDL Cholesterol" to "VLDL Cholesterol",
        "VLDL Cholesterol" to "VLDL Cholesterol",
        "Valproic Acid" to "Valproic Acid",
        "Valproic Acid" to "Valproic Acid",
        "Common Questions" to "Vancomycin",
        "Common Questions" to "Vancomycin",
        "Vitamin A" to "Vitamin A",
        "Vitamin A" to "Vitamin A",
        "Vitamin B12" to "Vitamin B12",
        "Vitamin B9" to "Vitamin B9",
        "Vitamin K" to "Vitamin K",
        "Vitamin K" to "Vitamin K",
        "WBC Count" to "WBC Count",
        "WNV Tests" to "WNV Tests",
        "Waldenstrom Macroglobulinemia" to "Waldenstrom Macroglobulinemia",
        "Wet Prep" to "Wet Prep",
        "White Count" to "White Count",
        "Widal Test" to "Widal Test",
        "Widal Test" to "Widal Test",
        "Wilson Disease" to "Wilson Disease",
        "Xa Inhibition" to "Xa Inhibition",
        "ZPP/Heme Ratio" to "ZPP/Heme Ratio",
        "Zika PRNT" to "Zika PRNT",
        "Zinc Protoporphyrin" to "Zinc Protoporphyrin",
        "Zinc Protoporphyrin" to "Zinc Protoporphyrin",
        "aCL Antibody" to "aCL Antibody",
        "anti-HBc, IgM" to "anti-HBc, IgM",
        "bcr-abl Oncogene" to "bcr-abl Oncogene",
        "hCG Pregnancy" to "hCG Pregnancy",
        "high-sensitivity troponin" to "high-sensitivity troponin",
        "p24 Antigen" to "p24 Antigen"
    )

    val oneWord = hashMapOf(
        "Netilmicin" to " Netilmicin",
        "17-OHP" to "17-Hydroxyprogesterone",
        "17-OHP" to "17-Hydroxyprogesterone",
        "17-OHP" to "17-OHP",
        "3-ANCA" to "3-ANCA",
        "HIAA" to "5-HIAA",
        "HIAA" to "5-HIAA",
        "5-HT" to "5-HT",
        "5-Hydroxytryptamine" to "5-Hydroxytryptamine",
        "A1AT" to "A1AT",
        "A1c" to "A1c",
        "AAT" to "AAT",
        "ABGs" to "ABGs",
        "ACA" to "ACA",
        "ACE" to "ACE",
        "ACPA" to "ACPA",
        "ACR" to "ACR",
        "ACT" to "ACT",
        "ACTA" to "ACTA",
        "ACTH" to "ACTH",
        "AChE" to "AChE",
        "AD" to "AD",
        "ADA" to "ADA",
        "ADB" to "ADB",
        "ADH" to "ADH",
        "ADN-B" to "ADN-B",
        "ADNase-B" to "ADNase-B",
        "AFP" to "AFP",
        "AFP-L3%" to "AFP-L3%",
        "AGPA" to "AGPA",
        "ALA" to "ALA",
        "ALB" to "ALB",
        "ALP" to "ALP",
        "ALT" to "ALT",
        "AMH" to "AMH",
        "AML-M3" to "AML-M3",
        "ANA" to "ANA",
        "APA" to "APA",
        "APCA" to "APCA",
        "APTT" to "APTT",
        "ARA" to "ARA",
        "ASA" to "ASA",
        "ASCA" to "ASCA",
        "ASLO" to "ASLO",
        "ASMA" to "ASMA",
        "AST" to "AST",
        "AVP" to "AVP",
        "Paracetamol" to "Acetaminophen",
        "Paracetamol" to "Acetaminophen",
        "Acetoacetate" to "Acetoacetate",
        "Acetone" to "Acetone",
        "Agglutinins" to "Agglutinins",
        "ALB" to "Albumin",
        "ALB" to "Albumin",
        "Alcohol" to "Alcohol",
        "Aldolase" to "Aldolase",
        "Aldolase" to "Aldolase",
        "Alkp" to "Alkp",
        "Allergies" to "Allergies",
        "Amethopterin" to "Amethopterin",
        "Amikacin" to "Amikacin",
        "Aminophylline" to "Aminophylline",
        "NH3" to "Ammonia",
        "NH3" to "Ammonia",
        "Amniocentesis" to "Amnio",
        "Amnio" to "Amnio",
        "Amniocentesis" to "Amniocentesis",
        "Amnio" to "Amniocentesis",
        "Amy" to "Amy",
        "Amy" to "Amylase",
        "Amy" to "Amylase",
        "AD" to "Androstenedione",
        "AD" to "Androstenedione",
        "Angina" to "Angina",
        "Anthrax" to "Anthrax",
        "Anti-CCP" to "Anti-CCP",
        "Anti-FXa" to "Anti-FXa",
        "Anti-GPA" to "Anti-GPA",
        "Anti-HAV" to "Anti-HAV",
        "Anti-HCV" to "Anti-HCV",
        "Anti-Jo-1" to "Anti-Jo-1",
        "Anti-LKM1" to "Anti-LKM-1",
        "Anti-LKM1" to "Anti-LKM-1",
        "Anti-LKM1" to "Anti-LKM1",
        "Anti-RNP" to "Anti-RNP",
        "Anti-Ribonucleoprotein" to "Anti-Ribonucleoprotein",
        "Anti-SSA" to "Anti-SSA",
        "Anti-SSB" to "Anti-SSB",
        "Anti-SmRNP" to "Anti-SmRNP",
        "Anti-TNF" to "Anti-TNF",
        "Anti-TPO" to "Anti-TPO",
        "Anti-Topoisomerase" to "Anti-Topoisomerase",
        "Anti-U(1)RNP" to "Anti-U(1)RNP",
        "anti-DNA" to "Anti-dsDNA",
        "anti-DNA" to "Anti-dsDNA",
        "Arthritis" to "Arthritis",
        "Aspirin" to "Aspirin",
        "Asthma" to "Asthma",
        "B2M" to "B2M",
        "BAC" to "BAC",
        "BAL" to "BAL",
        "BCGR" to "BCGR",
        "BCR/ABL" to "BCR-ABL1",
        "bcr-abl" to "BCR-ABL1",
        "Oncogene" to "BCR-ABL1",
        "BCR/ABL" to "BCR-ABL1",
        "bcr-abl" to "BCR-ABL1",
        "Oncogene" to "BCR-ABL1",
        "BCR/ABL" to "BCR/ABL",
        "BChE" to "BChE",
        "BLL" to "BLL",
        "BMP" to "BMP",
        "BRCA" to "BRCA",
        "BUN" to "BUN",
        "Babesiosis" to "Babesiosis",
        "Beta-hydroxybutyrate" to "Beta-hydroxybutyrate",
        "Bicarb" to "Bicarb",
        "TBIL" to "Bilirubin",
        "TBIL" to "Bilirubin",
        "Butyrylcholinesterase" to "Butyrylcholinesterase",
        "C-telopeptide" to "C-telopeptide",
        "C1" to "C1",
        "C1q" to "C1q",
        "C2" to "C2",
        "C3" to "C3",
        "C4" to "C4",
        "CA-Breast" to "CA-Breast",
        "CA-GI" to "CA-GI",
        "CBC" to "CBC",
        "Hemogram" to "CBC",
        "CCT" to "CCT",
        "CEA" to "CEA",
        "CGM" to "CGM",
        "CH100" to "CH100",
        "CH50" to "CH50",
        "CHS" to "CHS",
        "CK" to "CK",
        "CMP" to "CMP",
        "CPK" to "CPK",
        "CRCL" to "CRCL",
        "CRP" to "CRP",
        "CTx" to "CTx",
        "Thyrocalcitonin" to "Calcitonin",
        "Thyrocalcitonin" to "Calcitonin",
        "Cancer" to "Cancer",
        "Dopamine" to "Catecholamines",
        "Epinephrine" to "Catecholamines",
        "Norepinephrine" to "Catecholamines",
        "Dopamine" to "Catecholamines",
        "Epinephrine" to "Catecholamines",
        "Norepinephrine" to "Catecholamines",
        "CgA" to "CgA",
        "Cl" to "Chloride",
        "Cl" to "Chloride",
        "Cirrhosis" to "Cirrhosis",
        "Cl" to "Cl",
        "Cobalamin" to "Cobalamin",
        "C1" to "Complement",
        "C1q" to "Complement",
        "C2" to "Complement",
        "C3" to "Complement",
        "C4" to "Complement",
        "CH50" to "Complement",
        "CH100" to "Complement",
        "C1" to "Complement",
        "C1q" to "Complement",
        "C2" to "Complement",
        "C3" to "Complement",
        "C4" to "Complement",
        "CH50" to "Complement",
        "CH100" to "Complement",
        "Cu" to "Copper",
        "Cu" to "Copper",
        "Coproporphyrin" to "Coproporphyrin",
        "Corticotropin" to "Corticotropin",
        "DST" to "Cortisol",
        "DST" to "Cortisol",
        "Cotinine" to "Cotinine",
        "Creat" to "Creat",
        "Creat" to "Creatinine",
        "Creat" to "Creatinine",
        "CRCL" to "Creatinine Clearance",
        "CCT" to "Creatinine Clearance",
        "CRCL" to "Creatinine Clearance",
        "CCT" to "Creatinine Clearance",
        "Crit" to "Crit",
        "Cryocrit" to "Cryocrit",
        "Cryocrit" to "Cryoglobulins",
        "Cryoprotein" to "Cryoglobulins",
        "Cryocrit" to "Cryoglobulins",
        "Cryoprotein" to "Cryoglobulins",
        "Cryoprotein" to "Cryoprotein",
        "Cu" to "Cu",
        "Cytogenetics" to "Cytogenetics",
        "DAT" to "DAT",
        "DCP" to "DCP",
        "DD3" to "DD3",
        "DGP" to "DGP",
        "DHEA-SO4" to "DHEA-SO4",
        "DHEA-SO4" to "DHEAS",
        "DHEA-SO4" to "DHEAS",
        "DLDL" to "DLDL",
        "DNA-FIT" to "DNA-FIT",
        "DPD" to "DPD",
        "DRVVT" to "DRVVT",
        "DST" to "DST",
        "Dehydration" to "Dehydration",
        "Deoxypyridinoline" to "Deoxypyridinoline",
        "Diabetes" to "Diabetes",
        "Diarrhea" to "Diarrhea",
        "Dibekacin" to "Dibekacin",
        "Diff" to "Diff",
        "Dopamine" to "Dopamine",
        "EMA" to "EMA",
        "EPCAM" to "EPCAM",
        "EPO" to "EPO",
        "ERBB2" to "ERBB2",
        "ESR" to "ESR",
        "SPE" to "Electrophoresis",
        "SPEP" to "Electrophoresis",
        "UPE" to "Electrophoresis",
        "UPEP" to "Electrophoresis",
        "IFE" to "Electrophoresis",
        "Electrophoresis" to "Electrophoresis",
        "Epilepsy" to "Epilepsy",
        "Epinephrine" to "Epinephrine",
        "EPO" to "Erythropoietin",
        "EPO" to "Erythropoietin",
        "EtOH" to "EtOH",
        "Alcohol" to "Ethanol",
        "EtOH" to "Ethanol",
        "BAL" to "Ethanol",
        "BAC" to "Ethanol",
        "Alcohol" to "Ethanol",
        "EtOH" to "Ethanol",
        "BAL" to "Ethanol",
        "BAC" to "Ethanol",
        "FANA" to "FANA",
        "FE-1" to "FE-1",
        "FEP" to "FEP",
        "HES/Leukemia" to "FIP1L1-PDGFRA",
        "HES/Leukemia" to "FIP1L1-PDGFRA",
        "FIT" to "FIT",
        "FK506" to "FK506",
        "FLC" to "FLC",
        "FOBT" to "FOBT",
        "FSH" to "FSH",
        "FT3" to "FT3",
        "FTA-ABS" to "FTA-ABS",
        "Fibromyalgia" to "Fibromyalgia",
        "Folacin" to "Folacin",
        "Folate" to "Folate",
        "Follitropin" to "Follitropin",
        "GSP" to "Fructosamine",
        "GSP" to "Fructosamine",
        "G-6-PD" to "G-6-PD",
        "G-6-PD" to "G6PD",
        "G-6-PD" to "G6PD",
        "GBS" to "GBS",
        "GDH" to "GDH",
        "GGT" to "GGT",
        "GGTP" to "GGTP",
        "GH" to "GH",
        "GPT" to "GPT",
        "GSP" to "GSP",
        "GTP" to "GTP",
        "GTT" to "GTT",
        "Gamma-GT" to "Gamma-GT",
        "Gentamicin" to "Gentamicin",
        "Glycohemoglobin" to "Glycohemoglobin",
        "Gout" to "Gout",
        "H1N1" to "H1N1",
        "HBeAg" to "HBeAg",
        "HBsAg" to "HBsAg",
        "HCO3-" to "HCO3-",
        "HCV-PCR" to "HCV-PCR",
        "HCV-RNA" to "HCV-RNA",
        "HDL" to "HDL",
        "HDL-C" to "HDL-C",
        "HE4" to "HE4",
        "HER-1" to "HER-1",
        "ERBB2" to "HER2",
        "HER2/neu" to "HER2",
        "c-erbB-2" to "HER2",
        "ERBB2" to "HER2",
        "HER2/neu" to "HER2",
        "c-erbB-2" to "HER2",
        "HER2/neu" to "HER2/neu",
        "HES/Leukemia" to "HES/Leukemia",
        "HGH" to "HGH",
        "HIAA" to "HIAA",
        "HPT" to "HPT",
        "HPT" to "Haptoglobin",
        "Hp" to "Haptoglobin",
        "HPT" to "Haptoglobin",
        "Hp" to "Haptoglobin",
        "Hb" to "Hb",
        "HbA1c" to "HbA1c",
        "Hct" to "Hct",
        "Hct" to "Hematocrit",
        "Crit" to "Hematocrit",
        "PCV" to "Hematocrit",
        "Hct" to "Hematocrit",
        "Crit" to "Hematocrit",
        "PCV" to "Hematocrit",
        "Hemoccult" to "Hemoccult",
        "Hemochromatosis" to "Hemochromatosis",
        "Hgb" to "Hemoglobin",
        "Hb" to "Hemoglobin",
        "Hgb" to "Hemoglobin",
        "Hb" to "Hemoglobin",
        "Hemogram" to "Hemogram",
        "Hepatitis" to "Hepatitis",
        "Hgb" to "Hgb",
        "Hp" to "Hp",
        "Hypertension" to "Hypertension",
        "Hyperthyroidism" to "Hyperthyroidism",
        "Hypothyroidism" to "Hypothyroidism",
        "IAT" to "IAT",
        "IBC" to "IBC",
        "ICSH" to "ICSH",
        "IFE" to "IFE",
        "IGF-1" to "IGF-1",
        "IL-6" to "IL-6",
        "INR" to "INR",
        "IRT" to "IRT",
        "IgA" to "IgA",
        "IgG" to "IgG",
        "IgM" to "IgM",
        "Infertility" to "Infertility",
        "Influenza" to "Influenza",
        "IL-6" to "Interleukin-6",
        "IL-6" to "Interleukin-6",
        "Isepamicin" to "Isepamicin",
        "Jaundice" to "Jaundice",
        "K" to "K",
        "K-Ras" to "K-Ras",
        "Karyotype" to "Karyotype",
        "LA" to "LA",
        "LAC" to "LAC",
        "LDH" to "LDH",
        "LDL" to "LDL",
        "LDL-C" to "LDL-C",
        "LFTs" to "LFTs",
        "LH" to "LH",
        "LPS" to "LPS",
        "BLL" to "Lead",
        "BLL" to "Lead",
        "Leukemia" to "Leukemia",
        "LPS" to "Lipase",
        "LPS" to "Lipase",
        "Lp(a)" to "Lp(a)",
        "PAF-AH" to "Lp-PLA2",
        "PLAC" to "Lp-PLA2",
        "PAF-AH" to "Lp-PLA2",
        "PLAC" to "Lp-PLA2",
        "LA" to "Lupus",
        "LAC" to "Lupus",
        "PTT-LA" to "Lupus",
        "DRVVT" to "Lupus",
        "MRVVT" to "Lupus",
        "Lutropin" to "Lutropin",
        "Lymphoma" to "Lymphoma",
        "Lytes" to "Lytes",
        "MHA-TP" to "MHA-TP",
        "MIF" to "MIF",
        "MIH" to "MIH",
        "MIS" to "MIS",
        "MLH1" to "MLH1",
        "MMA" to "MMA",
        "MMF" to "MMF",
        "MPA" to "MPA",
        "MPO" to "MPO",
        "MPO-ANCA" to "MPO-ANCA",
        "MPV" to "MPV",
        "MRVVT" to "MRVVT",
        "MSAFP" to "MSAFP",
        "MSH2" to "MSH2",
        "MSH6" to "MSH6",
        "MTX " to "MTX ",
        "Mag" to "Mag",
        "Mg" to "Magnesium",
        "Mag" to "Magnesium",
        "Mg" to "Magnesium",
        "Mag" to "Magnesium",
        "Malabsorption" to "Malabsorption",
        "Malaria" to "Malaria",
        "Malnutrition" to "Malnutrition",
        "Mantoux" to "Mantoux",
        "Melanoma" to "Melanoma",
        "Menopause" to "Menopause",
        "Metanephrines" to "Metanephrines",
        "Metanephrines" to "Metanephrines",
        "MTX" to "Methotrexate",
        "Amethopterin" to "Methotrexate",
        "MTX" to "Methotrexate",
        "Amethopterin" to "Methotrexate",
        "Mg" to "Mg",
        "Microalbumin" to "Microalbumin",
        "Microminerals" to "Microminerals",
        "Micronutrients" to "Micronutrients",
        "Monospot" to "Monospot",
        "Mt-sDNA" to "Mt-sDNA",
        "N-telopeptide" to "N-telopeptide",
        "NH3" to "NH3",
        "NIPS" to "NIPS",
        "NIPT" to "NIPT",
        "NTx" to "NTx",
        "Na" to "Na",
        "Neuropathy" to "Neuropathy",
        "Nicotine" to "Nicotine",
        "Non-HDL" to "Non-HDL",
        "Non-HDL-C" to "Non-HDL-C",
        "Norepinephrine" to "Norepinephrine",
        "Normetanephrine" to "Normetanephrine",
        "Norovirus" to "Norovirus",
        "O&P" to "O&P",
        "OGTT" to "OGTT",
        "Osteoarthritis" to "Osteoarthritis",
        "Osteocalcin" to "Osteocalcin",
        "Osteoporosis" to "Osteoporosis",
        "P" to "P",
        "P1NP" to "P1NP",
        "PAF-AH" to "PAF-AH",
        "PBG" to "PBG",
        "DD3" to "PCA3",
        "DD3" to "PCA3",
        "PCHE" to "PCHE",
        "PCT" to "PCT",
        "PCV" to "PCV",
        "PDW" to "PDW",
        "PFA" to "PFA",
        "PFT" to "PFT",
        "PGSN" to "PGSN",
        "PLAC" to "PLAC",
        "PLT" to "PLT",
        "AML-M3" to "PML-RARA",
        "AML-M3" to "PML-RARA",
        "PMS2" to "PMS2",
        "PO4" to "PO4",
        "PPD" to "PPD",
        "PR3" to "PR3",
        "PR3-ANCA" to "PR3-ANCA",
        "PRA" to "PRA",
        "PRL" to "PRL",
        "PS1" to "PS1",
        "PSA" to "PSA",
        "PS1" to "PSEN1",
        "S182" to "PSEN1",
        "PS1" to "PSEN1",
        "S182" to "PSEN1",
        "PT" to "PT",
        "PTT" to "PTT",
        "PTT-LA" to "PTT-LA",
        "Pancreatitis" to "Pancreatitis",
        "Paracetamol" to "Paracetamol",
        "Parathormone" to "Parathormone",
        "Parotitis" to "Parotitis",
        "Parvovirus" to "Parvovirus",
        "Pb" to "Pb",
        "Phenobarb" to "Phenobarb",
        "Pb" to "Phenobarbital",
        "Phenobarb" to "Phenobarbital",
        "Pb" to "Phenobarbital",
        "Phenobarb" to "Phenobarbital",
        "Phosphate" to "Phosphate",
        "P" to "Phosphorus",
        "PO" to "Phosphorus",
        "4" to "Phosphorus",
        "Phosphate" to "Phosphorus",
        "P" to "Phosphorus",
        "PO" to "Phosphorus",
        "4" to "Phosphorus",
        "Phosphate" to "Phosphorus",
        "Plazomicin" to "Plazomicin",
        "Pneumonia" to "Pneumonia",
        "Porphobilinogen" to "Porphobilinogen",
        "Porphyria" to "Porphyria",
        "K" to "Potassium",
        "K" to "Potassium",
        "Preeclampsia" to "Preeclampsia",
        "Pregnancy" to "Pregnancy",
        "PCT" to "Procalcitonin",
        "PCT" to "Procalcitonin",
        "PGSN" to "Progesterone",
        "PGSN" to "Progesterone",
        "PRL" to "Prolactin",
        "PRL" to "Prolactin",
        "Protime" to "Protime",
        "Protoporphyrin" to "Protoporphyrin",
        "Pseudocholinesterase" to "Pseudocholinesterase",
        "RF" to "RF",
        "RPI" to "RPI",
        "RPR" to "RPR",
        "RSV" to "RSV",
        "Rapamycin" to "Rapamycin",
        "RPI" to "Reticulocytes",
        "RPI" to "Reticulocytes",
        "Retinol" to "Retinol",
        "Rubeola" to "Rubeola",
        "S182" to "S182",
        "SACE" to "SACE",
        "SFLC" to "SFLC",
        "SGOT" to "SGOT",
        "SGPT" to "SGPT",
        "SHBG" to "SHBG",
        "SMA" to "SMA",
        "SMRP" to "SMRP",
        "SPE" to "SPE",
        "SPEP" to "SPEP",
        "STEC" to "STEC",
        "Salsalate" to "Salsalate",
        "Sarcoidosis" to "Sarcoidosis",
        "Scl-70" to "Scl-70",
        "Scleroderma" to "Scleroderma",
        "Sepsis" to "Sepsis",
        "5-Hydroxytryptamine" to "Serotonin",
        "5-HT" to "Serotonin",
        "5-Hydroxytryptamine" to "Serotonin",
        "5-HT" to "Serotonin",
        "Shingles" to "Shingles",
        "Siderophilin" to "Siderophilin",
        "Rapamycin" to "Sirolimus",
        "Rapamycin" to "Sirolimus",
        "Na" to "Sodium",
        "Na" to "Sodium",
        "Somatotropin" to "Somatotropin",
        "Streptomycin" to "Streptomycin",
        "Stroke" to "Stroke",
        "T-Spot®" to "T-Spot®",
        "TAC" to "TAC",
        "TBII" to "TBII",
        "TBIL" to "TBIL",
        "TCGR" to "TCGR",
        "TCO2" to "TCO2",
        "TDM" to "TDM",
        "TG" to "TG",
        "TGB" to "TGB",
        "TIBC" to "TIBC",
        "TP" to "TP",
        "TPO" to "TPO",
        "TPPA" to "TPPA",
        "TRAP" to "TRAP",
        "TRAb" to "TRAb",
        "TRIG" to "TRIG",
        "TSH" to "TSH",
        "TSI" to "TSI",
        "TT" to "TT",
        "FK506" to "Tacrolimus",
        "TAC" to "Tacrolimus",
        "FK506" to "Tacrolimus",
        "TAC" to "Tacrolimus",
        "TeBG" to "TeBG",
        "TfR" to "TfR",
        "Tg" to "Tg",
        "TgAb" to "TgAb",
        "Thalassemia" to "Thalassemia",
        "Thymotaxin" to "Thymotaxin",
        "Thyrocalcitonin" to "Thyrocalcitonin",
        "Tg" to "Thyroglobulin",
        "TGB" to "Thyroglobulin",
        "Tg" to "Thyroglobulin",
        "TGB" to "Thyroglobulin",
        "Thyrotropin" to "Thyrotropin",
        "Thyroxine" to "Thyroxine",
        "TnI" to "TnI",
        "TnT" to "TnT",
        "Tobramycin" to "Tobramycin",
        "Transferrin" to "Transferrin",
        "TG" to "Triglycerides",
        "TRIG" to "Triglycerides",
        "TG" to "Triglycerides",
        "TRIG" to "Triglycerides",
        "Triiodothyronine" to "Triiodothyronine",
        "TnI" to "Troponin",
        "TnT" to "Troponin",
        "cTnI" to "Troponin",
        "cTnT" to "Troponin",
        "hs-troponin" to "Troponin",
        "TnI" to "Troponin",
        "TnT" to "Troponin",
        "cTnI" to "Troponin",
        "cTnT" to "Troponin",
        "hs-troponin" to "Troponin",
        "Tuberculosis" to "Tuberculosis",
        "UA" to "UA",
        "UACR" to "UACR",
        "UIBC" to "UIBC",
        "UPCR" to "UPCR",
        "UPE" to "UPE",
        "UPEP" to "UPEP",
        "UA" to "Urinalysis",
        "UA" to "Urinalysis",
        "Uroporphyrin" to "Uroporphyrin",
        "VAP" to "VAP",
        "VAP" to "VAP",
        "VDRL" to "VDRL",
        "VLDL" to "VLDL",
        "VLDL-C" to "VLDL-C",
        "VMAU" to "VMAU",
        "VWF:Ag" to "VWF:Ag",
        "VWF:RCo" to "VWF:RCo",
        "VZV" to "VZV",
        "Valproate" to "Valproate",
        "Vasculitis" to "Vasculitis",
        "Vasopressin" to "Vasopressin",
        "ZP" to "ZP",
        "ZPP" to "ZPP",
        "aPTT" to "aPTT",
        "anti-DNA" to "anti-DNA",
        "anti-HBc" to "anti-HBc",
        "anti-HBe" to "anti-HBe",
        "anti-HBs" to "anti-HBs",
        "c-erbB-2 " to "c-erbB-2 ",
        "cANCA" to "cANCA",
        "cGFR" to "cGFR",
        "cTnI" to "cTnI",
        "cTnT" to "cTnT",
        "cfDNA" to "cfDNA",
        "cffDNA" to "cffDNA",
        "erbB-1" to "erbB-1",
        "fFN" to "fFN",
        "gFOBT" to "gFOBT",
        "hrHPV" to "hrHPV",
        "hs-troponin" to "hs-troponin",
        "hsCRP" to "hsCRP",
        "iFOBT" to "iFOBT",
        "msAFP" to "msAFP",
        "pANCA" to "pANCA",
        "proBNP" to "proBNP",
        "sDNA" to "sDNA",
        "sTfR" to "sTfR",
        "tTG" to "tTG"
    )

}